.travis.yml
composer.json
tests/SDKTest.php

- Add `php-7.1` and `php-7.2` tests on Travis CI build.
- The `PHPUnit` will read `phpunit.xml ` configuration by default.
It's fine to remove this command option.

Enhance Travis CI setting

---

example.php
src/SDK/Language/JS.php
templates/js/package.json.twig
templates/js/tsconfig.json.twig
templates/js/types/index.d.ts.twig

This PR is to use the JS SDK in a TypeScript project by creating a types declaration file in the JS language itself, instead of creating a dedicated TS SDK.
Should help to solve #20

Add types declaration in JS SDK

---

templates/flutter/lib/client.dart.twig
templates/flutter/lib/services/service.dart.twig

The storage service getFilePreview was giving error because parameters like width, height, and quality were integers and Uri doesn't support int as queryParameters, as in URL there is no such thing as int or any other types except for String.
Looping through the params before passing to queryParams and converting any int and double values to string. It's done in two places at the moment
1. In storage service for localtion Uri and
2. In Client before sending get request.

The Storage service getFilePreview was giving error due to integer params

---

templates/flutter/lib/services/service.dart.twig
templates/flutter/pubspec.yaml.twig

@eldadfux this PR adds support for oAuth on Flutter Web using universal_html, as suggested, I have just redirected the web to the oAuth url. In documentation we need to add that, if we are building for flutter web, we need to pass success and failure URL, that is how it gets redirected.
The success case works fine, we get logged in and redirected. I am  not sure how it works for failure case, we should get redirected, but not know how we can handle the error case, as i was not able to reproduce a error case.

Adding support for oAuth using universal_html

---

templates/js/types/index.d.ts.twig

Method definitions was missing `?` from them indicating that they are optional parameter. 
Please let me know if there is anything that I missed.

fix(index.d.ts): optional parameters should have question mark

---

README.md

The examples themselves were removed, and so should the link

Removed link to examples

---

src/SDK/Language/CSharp.php
templates/csharp/docs/example.md.twig

Self-explanatory 👋 
Also changed to use double quotes for strings. Single quotes are for chars in C# 👍

feat(c#): adds code examples

---

templates/dotnet/docs/example.md.twig

Found some minor things to fix the docs:
- fixes comments to `//`
- fixes casing on method call
- fixes data type for response

fix(c#): example docs syntax

---

templates/dotnet/src/Appwrite/Client.cs.twig

In some occasions it is possible to transform headers like project or api key to a comma seperated list. This fix prevents it 👍 
> If the specified header is already present, values are added to the comma-separated list of values associated with the header.

fix(dotnet): prevent headers from being an array

---

tests/SDKTest.php

Run the library on .NET 3.1 (LTS) and 5.0 (Latest/Current) version.
This ensures major compability.

tests(dotnet); run lts and latest .net version

---

templates/flutter/lib/client.dart.twig
templates/flutter/pubspec.yaml.twig

As I described in https://github.com/appwrite/sdk-for-flutter/issues/14 we should use `package_info_plus` instead `package_info`. I didn't test the changes - I just changed it via GitHub UI.
Closes https://github.com/appwrite/sdk-for-flutter/issues/14

Switched from package_info to package_info_plus

---

templates/dart/.travis.yml.twig
templates/dart/lib/client.dart.twig

Hey, looks like I missed the await keyword, which doesn't catch the error so the exceptions are not working. This should fix that.

fix dart sdk exception missing await

---

src/SDK/Language/CLI.php
templates/cli/.travis.yml.twig

This PR adds a `twig` template to automate deployment of the CLI SDK upon tag creation.

Automate CLI SDK deployment to Docker Hub

---

.travis.yml
tests/resources/spec.json

Following this PR: https://github.com/appwrite/appwrite/pull/955, I have updated the Swagger test file we use to generate tests, the new spec will allow us to generate test SDKs that have new method that will allow us to call the new endpoints added to appwrite/appwrite. For the new endpoint to work we need to merge both PR, and deploy a new version of appwrite.io

Update test spec

---

templates/cli/app/services/client.php.twig
templates/cli/app/services/init.php.twig
templates/cli/install.sh.twig
templates/cli/src/Client.php.twig

* Prevent JWT related headers from being included in the CLI 
* Fix for https://github.com/appwrite/sdk-for-cli/issues/8

Feat disable jwt in CLI

---

templates/node/lib/client.js.twig

Header values were sent as lowercase as well, which was causing issue with the JWT token.

fix nodejs jwt issue

---

templates/web/src/sdk.ts.twig

- in some node.js versions, `url.search` is considered readonly

fix(web): prevent url.search to be readonly property

---

templates/node/lib/client.js.twig
templates/node/lib/services/service.js.twig

- fixes response type in the request config when request is of type `location`
- prevents encoding on binary files returned from the SDK method

fix(node): proper response type for location requests

---

templates/web/src/sdk.ts.twig

Before:
`method(required: bool, optional: string = 'default value')`
After:
`method(required: bool, optional?: string)`
After now optional value will be automatically undefined 👍🏻

fix(web): optional parameter default values

---

templates/php/src/Services/Service.php.twig

- add param checking
- added proper return type for files
before:
```php
public function updateDocument(string $collectionId, string $documentId, array $data, array $read = [], array $write = []):array
{
$path   = str_replace(['{collectionId}', '{documentId}'], [$collectionId, $documentId], '/database/collections/{collectionId}/documents/{documentId}');
$params = [];
$params['data'] = $data;
$params['read'] = $read;
$params['write'] = $write;
return $this->client->call(Client::METHOD_PATCH, $path, [
'content-type' => 'application/json',
], $params);
}
```
after:
```php
public function updateDocument(string $collectionId, string $documentId, array $data, array $read = null, array $write = null): array
{
if (empty($collectionId)) {
throw new AppwriteException('Missing required parameter: …
```

fix(php): overall improvements

---

templates/web/rollup.config.js.twig
tests/languages/web/index.html

- Changes iife usage from `Appwrite` namespace to `window`
- Usage is now `const sdk = new Appwrite()` or `const sdk = new window.Appwrite()`

fix(web): iife namespace to window

---

templates/cli/src/Client.php.twig
templates/cli/src/Parser.php.twig

- `protected` are usually dev friendlier than `private` method
- Fixed some indentations and coding standards
- Arrays should be casted as `array` and not `Array`

Updated coding conventions

---

example.php
src/SDK/SDK.php

* Remove Unused Java and Typescript SDK generation
* When copying files, create directories in destination path if it doesn't exist
* Do not load twig templates if scope is `copy`  
* Added a link to the production Swagger spec for convenience

feat: improvements to sdk-generator

---

templates/cli/src/Client.php.twig

Allow commands ( like `appwrite version`) that do not require a network call, to be executed without running `appwrite init`

fix: allow cli version command without appwrite init

---

templates/flutter/lib/src/client_io.dart.twig

this should fix flutter auth not finding the key parameter when trying to create an OAuth session

fixing flutter web auth not finding

---

src/SDK/Language/Dart.php
src/SDK/Language/Flutter.php
templates/dart/lib/client_browser.dart.twig
templates/dart/lib/client_io.dart.twig
templates/flutter/lib/client_browser.dart.twig
templates/flutter/lib/client_io.dart.twig
templates/flutter/lib/package.dart.twig
templates/flutter/lib/realtime_browser.dart.twig
templates/flutter/lib/realtime_io.dart.twig
templates/flutter/lib/src/client_io.dart.twig
tests/languages/android/ServiceTest.kt
tests/languages/flutter/tests.dart
tests/languages/web/index.html

* Fix null pointer exception while creating OAuth2 session
* Export RealtimeMessage
* Export, separate IO and Browser clients for Flutter (Client and Realtime as well) and Dart (Client)

Fix flutter exports

---

src/Spec/Swagger2.php
templates/flutter/lib/package.dart.twig
templates/flutter/lib/src/models/model.dart.twig
templates/flutter/lib/src/realtime_mixin.dart.twig
templates/flutter/lib/src/realtime_subscription.dart.twig

- Fix realtime close and reconnect working only 1 out of two times due to future returning too early
- Add dart doc comments to newly added response models

Fix-realtime-and-doc-comments

---

templates/ruby/lib/container/client.rb.twig

Appropriately handle empty or non-JSON response bodies
Closes #289

Fix Ruby handling non-JSON responses

---

src/SDK/Language/Android.php
src/SDK/Language/Kotlin.php
templates/android/.github/workflows/publish.yml
templates/android/build.gradle.twig
templates/android/example-java/build.gradle.twig
templates/android/example-java/src/main/AndroidManifest.xml
templates/android/example-java/src/main/java/io/appwrite/example_java/MainActivity.java.twig
templates/android/example/build.gradle.twig
templates/android/example/src/main/AndroidManifest.xml
templates/android/example/src/main/java/io/appwrite/android/ui/accounts/AccountsViewModel.kt.twig
templates/android/gradle/wrapper/gradle-wrapper.properties
templates/android/library/build.gradle.twig
templates/android/library/src/main/java/io/appwrite/Client.kt.twig
templates/android/library/src/main/java/io/appwrite/exceptions/Exception.kt.twig
templates/android/library/src/main/java/io/appwrite/json/PreciseNumberAdapter.kt.twig
templates/android/library/src/main/java/io/appwrite/models/Model.kt.twig
templates/android/library/src/main/java/io/appwrite/services/ServiceTemplate.kt.twig
tests/SDKTest.php
tests/languages/android/ServiceTest.kt

Add Android response models
Update dependencies
Update to Java 11
Target Android 12

Feat android response models

---

templates/node/lib/query.js.twig

Code:
```
const sdk = require("node-appwrite");
console.log(sdk.Query.equal("name", "Matej"));
```
Before this PR:
```
console.log(sdk.Query.equal("name", "Matej"));
^
TypeError: sdk.Query.equal is not a function
at Object.<anonymous> (/Users/meldiron/Desktop/delme/aw10del/app.js:2:23)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:17:47
```
After this PR:
```
name.equal("Matej")
```

Added proper export for Query class

---

templates/web/src/sdk.ts.twig

Snippets from generated SDK:
```typescript
export type UploadProgress = {
$id: string;
progress: number;
sizeUploaded: number;
chunksTotal: number;
chunksUploaded: number;
}
```
```typescript
createTag: async (functionId: string, command: string, code: File, onProgress = (progress: UploadProgress) => {}): Promise<Models.Tag> => {
```
```typescript
if (onProgress) {
onProgress({
$id: response.$id,
progress: Math.min((counter + 1) * Appwrite.CHUNK_SIZE, size) / size * 100,
sizeUploaded: end+1,
chunksTotal: response.chunksTotal,
chunksUploaded: response.chunksUploaded
});
}
```

Fix: Added UploadProgress type

---

templates/cli/lib/commands/deploy.js.twig
templates/cli/lib/commands/init.js.twig

This PR fixes the CLI deleting all function variables when deploying a function, it also removes environment variables from the stored data as this could potentially be a security problem.

Fix CLI deleting variables on function deploy

---

README.md

It seems that specification may not agree in number with other words in this phrase.

Grammatical mistake

---

templates/cli/lib/commands/command.js.twig

Currently, prefs are passed as string into CLI, but are expected as object by server, resulting in invalid 4XX error:
With these changes, if expected type is object, input from CLI is automatically parsed with `JSON.parse()`, resulting in successful execution:

Fix: JSON object parsing

---

templates/cli/lib/commands/command.js.twig

This PR adds a catch to the HTTP calls made in the CLI when we are deploying functions. The catch will make sure we delete the archive then will throw the error again so our handler can deal with it.

Fix Archive not being deleted when the deploy request fails

---

example.php
templates/cli/install.ps1.twig

- File must end with `.exe` for it to work. Instead of making `Appwrite` file, we now make `appwrite.exe` inside `Appwrite` folder
- After installation, if we change PATH env, we also refresh it, so you can instantly use without restarting powershell. that's something like `source` on linux

Fix: Powershell install

---

src/SDK/Language/Deno.php
src/SDK/Language/Kotlin.php
src/SDK/Language/Node.php
src/SDK/Language/PHP.php
src/SDK/Language/Python.php
src/SDK/Language/Ruby.php

Currently, the documentation for creating files passes in a file binary. Our current implementation only accepts a file path. This must be corrected in the documentation for all SDKs.
Node SDK ✅
Deno SDK ✅
PHP SDK ✅
Python SDK ✅
Ruby SDK ✅
Dart SDK ✅ (this hasn't changed)
Kotlin (Java) ✅ (this hasn't changed)
Kotlin (Kotlin) ✅ (this hasn't changed)
Swift ✅ (this hasn't changed)
Related to
https://github.com/appwrite/sdk-for-node/issues/32

Fix File Create Docs

---

composer.lock
templates/python/package/services/service.py.twig

Currently, if you pass `True` or `False`into multiform data, it fails.
This has already been addressed in Node, so I am adding the same fix to Python..
Related issues: https://github.com/appwrite/appwrite/issues/3169
QA code:
```py
from appwrite.client import Client
from appwrite.services.users import Users
from appwrite.services.functions import Functions
client = Client()
(client
.set_endpoint('https://8080-appwrite-appwrite-....gitpod.io/v1') # Your API Endpoint
.set_project('...') # Your project ID
.set_key('...') # Your secret API key
)
func = Functions(client)
result = func.create_deployment('6275052b0a821a3ca033', 'index.py', 'code.tar.gz', True)
print(result)
```
Results:

Fix: [PYTHON] boolean in FormData

---

composer.lock
src/Spec/Swagger2.php
templates/deno/src/models.d.ts.twig

Issue: https://github.com/appwrite/sdk-for-deno/issues/7
Impementation generates:
```
export type AttributeList = {
sum: number;
attributes: AttributeBoolean[] | AttributeInteger[] | AttributeFloat[] | AttributeEmail[] | AttributeEnum[] | AttributeUrl[] | AttributeIp[] | AttributeString[];
}
```

Fix: Deno anyOf types

---

templates/deno/src/services/service.ts.twig

Currently, if you upload a 7MB file, the whole 10MB is uploaded, the rest of the data being zeros:
This PR fixes the issue and shrinks the buffer to remove zeros, making the file exact size.

Fix: Deno Chunk Upload

---

templates/web/src/sdk.ts.twig

As reported here: https://github.com/appwrite/appwrite/issues/3209
You create file input. you get `event.target.value`. You get an array of files. I consider it a common mistake to try to pass the value directly into Appwrite.
Currently, Appwrite doesn't tell anything. During chunk upload logic the size will be `undefined`, resulting in 0 chunks being uploaded, but also probably no error thrown.
With this new logic, we check if a variable type is `File`, and throw a proper error if you pass an array, buffer, file path, base64, or anything that is unsupported.
Example of generated code:

Fix: Web file error message

---

templates/cli/lib/commands/deploy.js.twig
templates/cli/lib/questions.js.twig

Currently if you:
```
appwrite login
appwrite init project
appwrite init function
appwrite deploy function
```
It fails in deploy function with message:
Problem solved by applying the same strategy as there already is regarding deploy collections - instead of passing BigIntJSON objects, we pass strings and then parse them. This seems to be a limitation of `inquirer` library.

Fix: CLI function deploy

---

src/SDK/Language/Swift.php

Current example shows an empty line for the Apple Client SDK:
The database guide uses an empty dictionary `[:]`:
The newly generated examples will match the database guide:

Add empty dictionary to Swift SDK examples.

---

templates/swift/Sources/Client.swift.twig

- Collect body bytes when returning `ByteBuffer` for downloads
Resolves https://github.com/appwrite/sdk-for-apple/issues/16

Collect body bytes

---

templates/node/lib/services/service.js.twig

The code works if parameter is `file`, but not if `code` (when functions.createDeployment())

Fix: File upload var name

---

composer.lock
example.php
templates/cli/lib/commands/deploy.js.twig
templates/cli/lib/commands/generic.js.twig
templates/cli/lib/commands/init.js.twig
templates/cli/lib/parser.js.twig
templates/cli/lib/questions.js.twig

- Removed `--all` option from `appwrite init`
- Removed `--all` option from `appwrite deploy`
- Added `--all` option to `appwrite init collection`
- Added `--all` option to `appwrite deploy collection`
- Added `--all` option to `appwrite deploy function`
- During `appwrite init project` it now also asks for Project ID
- During `appwrite init function` it now also asks for Function ID
- During `appwrite init collection` you can now pick one or many databases to pull collections from
- Added `--databaseId <id>` to `appwrite init collection`
- Fixed `databases` command descriton
- Fixed `appwrite login`
- `appwrite database` is now `appwrite databases`
- each `appwrite databases` command now required `--databaseId`
- `appwrite account createSession` is now `appwrite account …

Feat: Improve CLI after 0.15

---

templates/ruby/docs/example.md.twig

New generated examples will look like this:
```ruby
require 'appwrite'
client = Appwrite::Client.new
client
.set_endpoint('https://[HOSTNAME_OR_IP]/v1') # Your API Endpoint
.set_project('5df5acd0d48c2') # Your project ID
databases = Appwrite::Databases.new(client, database_id:'[DATABASE_ID]')
response = databases.create(name: '[NAME]')
puts response.inspect
```

Added parameter for DB constructor to be named constructor

---

templates/flutter/lib/src/client_io.dart.twig
templates/flutter/lib/src/realtime_io.dart.twig

- Prevent concurrent init calls in Flutter SDK
Existing test
- #417 
YES

Flutter: check if init is already in progress

---

templates/deno/src/query.ts.twig

Implements new query syntax into Query class helper. We went from `name.equal("Matej", "Eldad")` to `equal("name", ["Matej", "Eldad"])`.
Implemented in:
WIP
x
Yes

Feat: Queries upgrade

---

templates/cli/lib/questions.js.twig

When generating a function with the Appwrite CLI, it prompts for an ID, and provides myAwesomeFunction as the default. This should be unique() instead if they don't enter anything so it generates a random ID.
NIL
Yes

Change default Function ID to unique()

---

templates/flutter/lib/src/client_browser.dart.twig
templates/flutter/lib/src/client_io.dart.twig
templates/flutter/pubspec.yaml.twig

Changes the package dependency from [flutter_web_auth](https://pub.dev/packages/flutter_web_auth) to [flutter_web_auth_2](https://pub.dev/packages/flutter_web_auth_2) because the original dependency can be considered abandoned.
I forked the `sdk_for_flutter` read-only repo at https://github.com/startcommerce/appwrite_flutter and tested the same changes by authenticating with GitHub OAuth in a Flutter web application.
See the following issue https://github.com/appwrite/sdk-for-flutter/issues/64.
Affirmative. Will. Robinson.

Update to use flutter_web_auth_2 dependency

---

src/SDK/Language/PHP.php
tests/resources/spec.json

Before:
```php
public function list(string$search = null, int $limit = null, int $offset = null, string$cursor = null, string$cursorDirection = null, string$orderType = null): array
```
> Syntax errors
After:
```php
public function list(string $search = null, int $limit = null, int $offset = null, string $cursor = null, string $cursorDirection = null, string $orderType = null): array
```
x
Yes

Fix PHP param syntax

---

templates/flutter/pubspec.yaml.twig

Upgrades [`flutter_web_auth_2`](https://pub.dev/packages/flutter_web_auth_2) dependencies to latest version. The latest version of the plugin supports windows implementation.
N/A
See PR [#7](https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/7) of [flutter_web_auth](https://github.com/ThexXTURBOXx/flutter_web_auth_2/)
Yes😄

Bump dependencies flutter

---

templates/cli/lib/commands/deploy.js.twig

After running `appwrite deploy collection`, all is created but collection does not have permissions (collection-level). This PR fixes it.
None
x
Yes

Fix: CLI: Missing permissions after deploy

---

templates/android/library/src/main/java/io/appwrite/Role.kt.twig
templates/dart/lib/role.dart.twig
templates/deno/src/role.ts.twig
templates/kotlin/src/main/kotlin/io/appwrite/Role.kt.twig
templates/node/lib/role.js.twig
templates/php/src/Role.php.twig
templates/python/package/role.py.twig
templates/ruby/lib/container/role.rb.twig
templates/swift/Sources/Role.swift.twig
templates/web/src/role.ts.twig

Remove the `status` role method as this functionality is part of the `user` and `users` roles
Existing tests
Yes

Remove redundant status role method

---

templates/cli/lib/commands/deploy.js.twig
templates/cli/lib/commands/init.js.twig
templates/cli/lib/questions.js.twig

- Deploy variables from JSON config file. Warn if we are about to delete them first
- Introduce `--yes` into both `deploy function/collection`. If passed, no questions asked. Better CI/CD support
https://user-images.githubusercontent.com/19310830/191289338-06ecf7e1-2dfc-48d2-8276-50cf9c9a355a.mp4
https://user-images.githubusercontent.com/19310830/191289328-330b4b24-fec3-47d8-88f0-75ea3d1f419a.mp4
x
Yes! 😎

Feat: CLI function variables

---

templates/flutter/pubspec.yaml.twig

It upgrades the `device_info_plus` dependency for Flutter.
Since the major version was updated, apps can't use `appwrite` together with the latest version of `device_info_plus` at the moment (at least not without`dependency_overrides`).
Yes

Upgrade device_info_plus for Flutter

---

templates/graphql/docs/example.md.twig

`$` is reserved so we had to replace all `$` with `_`
Manually generated examples.
databases/get-document.md:
```graphql
query {
databasesGetDocument(
databaseId: "[DATABASE_ID]",
collectionId: "[COLLECTION_ID]",
documentId: "[DOCUMENT_ID]"
) {
_id
_collectionId
_databaseId
_createdAt
_updatedAt
_permissions
data
}
}
```
account/get.md:
```graphql
query {
accountGet {
_id
_createdAt
_updatedAt
name
registration
status
passwordUpdate
email
phone
emailVerification
phoneVerification
prefs
}
}
```
None
Yes

Make sure attributes with $ use _ instead in GraphQL examples

---

templates/graphql/docs/example.md.twig

GraphQL requests must always specify the attributes to be returned in the request. This PR ensures response models are processed recursively so that all examples display all attributes for nested models.
Manually generated.
databases/list-documents.md:
```graphql
query {
databasesListDocuments(
databaseId: "[DATABASE_ID]",
collectionId: "[COLLECTION_ID]"
) {
total
documents {
_id
_collectionId
_databaseId
_createdAt
_updatedAt
_permissions
data
}
}
}
```
teams/get.md:
```graphql
query {
teamsGet(
teamId: "[TEAM_ID]"
) {
_id
_createdAt
_updatedAt
name
total
}
}
```
users/list.md:
```graphql
query {
usersList {
total
users {
_id
_createdAt
_updatedAt
name
password
hash
hashOptions
registration
status
passwordUpdate
email
phone
emailVerification
phoneVerification
prefs {
data
}
}
}
}
```
* …

Recursively display response model attributes for graphql examples

---

templates/node/lib/client.js.twig

Some API calls result in an error like:
```
Error: unexpected end of file
at Client.call (.../appwrite-playground-for-node/node_modules/node-appwrite/lib/client.js:176:23)
at processTicksAndRejections (.../appwrite-playground-for-node/lib/internal/process/task_queues.js:96:5)
at async Databases.listCollections (.../appwrite-playground-for-node/node_modules/node-appwrite/lib/services/databases.js:186:16)
at async listCollections (.../appwrite-playground-for-node/src/app.js:135:22)
at async runAllTasks (.../appwrite-playground-for-node/src/app.js:504:5) {code: undefined, type: undefined, response: undefined, stack: 'Error: unexpected end of file
at Client.c…ppwrite-playground-for-node/src/app.js:504:5)', message: 'unexpected end of file'}
```
This appears to be a bug in axios. See …

Fix "unexpected end of file" error

---

templates/node/base/requests/file.twig

`stream.write()` must handle errors or else undefined behavior may occur. See https://nodejs.org/api/stream.html\#errors-while-writing for more info.
Manually tested by uploading a file bigger than 5MB and less than 5MB
* https://github.com/appwrite/sdk-for-node/issues/45
Yes

Ensure node file upload captures and throws errors

---

templates/swift/Sources/Services/Service.swift.twig
templates/swift/Sources/WebSockets/WebSocketClient.swift.twig
tests/AppleSwift55Test.php
tests/languages/apple/Tests.swift

Fixes "hang risk" warnings for realtime in Xcode 14: `Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions`
- Move thread event loop group creation to a background thread
- Remove blocking wait for channel upgrade
- Remove async from webauth methods
Manual test
Related https://github.com/appwrite/sdk-for-apple/issues/24
Yes

Fix Xcode 14 hang risk warnings

---

templates/cli/lib/commands/deploy.js.twig
templates/cli/lib/commands/init.js.twig
templates/cli/lib/config.js.twig
templates/cli/lib/questions.js.twig

As implemented by init&deploy collection, this PR adds the same logic for teams. It' common practice to have a predefined structure of teams (mods/admins/...), just like it's common for databases. Since appwrite.json is supposed to be a source of truth for initial setup of Appwrite project, it should include structure of teams.
This PR gets us one small step closer to "Deploy to Appwrite" 1-click setup.
https://user-images.githubusercontent.com/19310830/193421101-6c296c12-ab48-45e3-80de-63f68bd91b6c.mp4
x
Yes

Feat: CLI teams init&deploy

---

templates/flutter/lib/src/realtime_mixin.dart.twig

- Propagate websocket close and error to realtime subscription
https://github.com/appwrite/sdk-for-flutter/issues/108

Fix Flutter websocket issue

---

templates/cli/lib/commands/init.js.twig

Removes keys `$createdAt`, `$updatedAt`, `total` from appwrite.json
x
Yes

Fix: Extra appwrite.json keys

---

templates/flutter/lib/src/client_io.dart.twig

- Set `preferEphemeral` to true so android and iOS doesn't keep activity history of OAuth web browser (solves an issue raised in discord that after completing OAuth login, android hardware back key was taking back to web browser again)

Oauth clear hsitory

---

CONTRIBUTING.md
src/SDK/Language/Flutter.php
src/Spec/Swagger2.php
templates/dart/lib/id.dart.twig
templates/dart/lib/package.dart.twig
templates/flutter/base/requests/api.twig
templates/flutter/example/pubspec.yaml.twig
templates/flutter/lib/package.dart.twig
templates/flutter/lib/src/client.dart.twig
templates/flutter/lib/src/client_base.dart.twig
templates/flutter/lib/src/client_browser.dart.twig
templates/flutter/lib/src/client_io.dart.twig
templates/flutter/lib/src/client_offline_mixin.dart.twig
templates/flutter/lib/src/offline_db.dart.twig
templates/flutter/pubspec.yaml.twig
tests/DartBetaTest.php
tests/DartStableTest.php
tests/FlutterBetaTest.php
tests/FlutterStableTest.php
tests/languages/dart/tests.dart
tests/languages/flutter/tests.dart
tests/resources/spec.json

Update the Flutter SDK to add Offline Support.
Manual
TODO
Yes

Update Flutter SDK to add offline support

---

templates/flutter/lib/src/client_offline_mixin.dart.twig

spec.endpoint is actually set to https://HOSTNAME/v1 which can't be used to check the online status. However, sdk.url is https://appwrite.io which can be used to check for internet connectivity.
Manual
Previous PR:
* https://github.com/appwrite/sdk-generator/pull/618
Yes

Fix url used for checking offline status

---

templates/cli/lib/commands/command.js.twig

Makes it possible to set array attribute to empty array in Appwrite CLI.
Generated code:
```js
databases
.command(`createDocument`)
.description(`Create a new Document. Before using this route, you should create a new collection resource using either a [server integration](/docs/server/databases#databasesCreateCollection) API or directly from your database console.`)
.requiredOption(`--databaseId <databaseId>`, `Database ID.`)
.requiredOption(`--collectionId <collectionId>`, `Collection ID. You can create a new collection using the Database service [server integration](https://appwrite.io/docs/server/databases#databasesCreateCollection). Make sure to define attributes before creating documents.`)
.requiredOption(`--documentId <documentId>`, `Document ID. Choose a custom ID or generate a …
```

Allow empty array param

---

templates/flutter/pubspec.yaml.twig

pub.dev incorrectly shows that the appwrite flutter SDK doesn't support web when it does. This overrides what pub.dev detects to explicitly include web as supported.
Manual:
* https://github.com/appwrite/sdk-for-flutter/issues/138
Yes

Update flutter SDK supported platforms list

---

templates/node/index.d.ts.twig
templates/node/package.json.twig

Delete methods return empty string so the type should be a string.
getAttribute() returns any one of the possible attributes so we'll use
any for now. In the future, we can look into supporting a union type.
Fix missing buffer type error
Fix missing NodeJS type
delete method:
getAttribute(): 
fix buffer and nodejs type errors:
None
Yes

Fix node types

---

templates/node/index.d.ts.twig

1.3.x introduced new Query methods and they were added to the Query class, but were missing from index.d.ts.
Manually generated SDK:
* https://github.com/appwrite/sdk-for-node/pull/55 - [Comment](https://github.com/appwrite/sdk-for-node/pull/55/files#r1180009818)
Yes

Add typing for new Query methods in the Node SDK

---

templates/web/package.json.twig

For projects with moduleResolution set to bundler in tsconfig.json, the types must be exported in the package.json file.
Closes: https://github.com/appwrite/sdk-for-web/issues/54
Manually added in a new project and I no longer see the error:
I also added it to another TS project of mine that has `moduleResolution` set to `node` and that still worked as expected:
* https://github.com/appwrite/sdk-for-web/issues/54
Yes

Fix typing exports for web SDK

---

templates/web/src/services/template.ts.twig

- Remove additional white spaces in Web sdk

remove additional white spaces

---

templates/dart/pubspec.yaml.twig
templates/flutter/pubspec.yaml.twig

Upgrade dependencies of Flutter and Dart to make it Dart 3.0 Ready
Manual QA
Fixes [#5583](https://github.com/appwrite/appwrite/issues/5583)
Yes

Upgrade dependencies Flutter and dart

---

templates/cli/lib/parser.js.twig

Creates user successfully without errors.
* https://github.com/appwrite/sdk-for-cli/issues/81
Yes

Fix creating a user throws an error 

---

templates/cli/README.md.twig

Use php 8.1 with SDK generator, and 7.4 no longer works with SDK-generator.
- Imrove SDK CLI readme, contribution section
- https://github.com/appwrite/sdk-generator/issues/666
YES

improve CLI readme contribution part

---

src/SDK/Language/Dart.php
src/SDK/Language/Flutter.php
templates/dart/test/id_test.dart.twig
templates/dart/test/permission_test.dart.twig
templates/dart/test/query_test.dart.twig
templates/dart/test/role_test.dart.twig
templates/dart/test/src/enums_test.dart.twig
templates/dart/test/src/models/model_test.dart.twig
templates/dart/test/src/response_test.dart.twig
templates/flutter/test/src/cookie_manager_test.dart.twig

Add test cases for helpers and models to improve test coverage score.
Manual:
Tests passing w/ 65% test coverage.

Add tests for helpers and moels to Flutter and Dart SDKs

---

templates/dart/README.md.twig
templates/dart/lib/id.dart.twig
templates/dart/lib/models.dart.twig
templates/dart/lib/package.dart.twig
templates/dart/lib/permission.dart.twig
templates/dart/lib/query.dart.twig
templates/dart/lib/role.dart.twig
templates/dart/lib/services/service.dart.twig
templates/dart/lib/src/client.dart.twig
templates/dart/lib/src/enums.dart.twig
templates/dart/lib/src/exception.dart.twig
templates/dart/lib/src/input_file.dart.twig
templates/dart/lib/src/response.dart.twig
templates/dart/lib/src/upload_progress.dart.twig
templates/flutter/README.md.twig
templates/flutter/lib/package.dart.twig
templates/flutter/lib/services/service.dart.twig
templates/flutter/lib/src/client.dart.twig
templates/flutter/lib/src/realtime.dart.twig
templates/flutter/lib/src/realtime_message.dart.twig
templates/flutter/lib/src/realtime_subscription.dart.twig

Add docs that will appear in IDEs and on pub.dev.
Manually generated SDKs:
* https://github.com/appwrite/sdk-for-flutter/compare/feat-152-doc-comments
* https://github.com/appwrite/sdk-for-flutter/issues/152
* https://github.com/appwrite/sdk-for-flutter/compare/feat-152-doc-comments
Yes

Add inline doc comments to the Dart and Flutter SDKs

---

src/SDK/Language/Dart.php
src/SDK/Language/Flutter.php
templates/dart/pubspec.yaml.twig
templates/dart/test/id_test.dart.twig
templates/dart/test/permission_test.dart.twig
templates/dart/test/query_test.dart.twig
templates/dart/test/role_test.dart.twig
templates/dart/test/services/service_test.dart.twig
templates/dart/test/src/enums_test.dart.twig
templates/dart/test/src/models/model_test.dart.twig
templates/dart/test/src/response_test.dart.twig

Moving it to dart allows them to be re-used between both SDKs.
Closes: https://github.com/appwrite/sdk-for-flutter/issues/90
Manual Dart:
Manual Flutter:
* https://github.com/appwrite/sdk-for-flutter/issues/90
* https://github.com/appwrite/sdk-generator/pull/673
Yes

Move flutter service tests to dart

---

templates/dart/pubspec.yaml.twig
templates/flutter/pubspec.yaml.twig

This fixes the CI because the mockito 5.4.1 doesn't work with our version of flutter_test:
> Because mockito >=5.4.1 depends on matcher ^0.12.15 and every version of flutter_test from sdk depends on matcher 0.12.13, mockito >=5.4.1 is incompatible with flutter_test from sdk.
CI tests for flutter should pass
None
Yes

Downgrade mockito in Flutter and Dart SDKs

---

templates/dotnet/src/Appwrite/Exception.cs.twig

Adds missing type field to the AppwriteException class
Generate example SDK using the `example.php` file in the repo
- Earlier
- Now
No
Yes

fix: Add type field to AppwriteException class to .NET SDK

---

templates/dotnet/src/Appwrite/Exception.cs.twig

Add missing semicolon in constructor
#691 
Yes

fix: Add missing semicolon in AppwriteException constructor in .NET SDK

---

templates/dotnet/base/params.twig
templates/dotnet/base/requests/api.twig
templates/dotnet/base/requests/file.twig
templates/dotnet/base/requests/location.twig

- renames `headers` var to `apiHeaders` to avoid conflicts

fix: headers keyword for .net

---

templates/cli/lib/parser.js.twig

Fix errors like:
```
appwrite -v                                                          
pkg/prelude/bootstrap.js:1740
throw error;
^
TypeError: (intermediate value).description(...).configureHelp is not a function
at Object.<anonymous> (/snapshot/sdk-for-cli/lib/commands/assistant.js:13:90)
at Module._compile (pkg/prelude/bootstrap.js:1794:22)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at Module.require (pkg/prelude/bootstrap.js:1719:31)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/snapshot/sdk-for-cli/index.js:18:23)
at Module._compile …
```

Fix CLI missing command descriptions

---

templates/swift/Sources/Services/Service.swift.twig
templates/swift/base/requests/oauth.twig

- Fix XPC connection interrupted when app in background during OAuth login for Apple
Manual test
https://github.com/appwrite/appwrite/issues/6206
Yes

Fix apple xpc interrupt

---

templates/dart/lib/src/client_browser.dart.twig
templates/dart/lib/src/client_io.dart.twig
templates/flutter/lib/src/client_browser.dart.twig
templates/flutter/lib/src/client_io.dart.twig

The chunk length is supposed to be equal to CHUNK_SIZE or whatever is left for the file, but the - 1 for the end made the chunk 1 less than the correct length (due to the way getRange works).
For example, see the chunk length when using fromBytes():
vs fromPath():
Manually tested and was able to upload the file successfully:
In addition, comparing the uploaded file with the original file showed they were the same:
* https://github.com/appwrite/appwrite/issues/6304
Yes

Fix dart SDK not uploading correct length of chunks

---

templates/node/lib/client.js.twig

The NODE_TLS_REJECT_UNAUTHORIZED env variable will disable SSL checks for all requests. This PR changes the node SDK to only disable SSL checks for Appwrite related requests by passing an option to axios.
Fixes https://github.com/appwrite/appwrite/issues/6832
Before change:
After change:
Without calling setSelfSigned():
* https://github.com/appwrite/appwrite/issues/6832
Yes

Update how the node SDK handles self signed requests

---

src/SDK/Language/Deno.php
templates/deno/src/exception.ts.twig
templates/deno/test/id.test.ts.twig
templates/deno/test/permission.test.ts.twig
templates/deno/test/query.test.ts.twig
templates/deno/test/role.test.ts.twig
templates/deno/test/services/service.test.ts.twig

This PR adds unit tests for the Deno SDK.
Generate the SDK, then run `deno test` in the generated SDK's directory.
#680 
Yup

Unit Tests - Deno

---

src/SDK/Language/PHP.php
templates/php/composer.json.twig
templates/php/tests/IDTest.php.twig
templates/php/tests/PermissionTest.php.twig
templates/php/tests/QueryTest.php.twig
templates/php/tests/RoleTest.php.twig
templates/php/tests/Services/ServiceTest.php.twig

This PR adds generated unit tests to the PHP SDK.
Generate the SDK, install composer dependencies, then run `vendor/bin/phpunit tests` in the SDK's directory.
#680 
Yup

Unit Tests - PHP

---

templates/ruby/lib/container/client.rb.twig

Fix ruby not removing nil values from params before passing to the API
Manual test 

Remove nil values from params

---

templates/python/package/input_file.py.twig

The file name is currently optional in our InputFile.from_bytes for Python. 
This will give you an error 100% of the time because you can't infer a filename from bytes.
The error message will be something like:
```
/Users/wen/PycharmProjects/test-scripts/venv/bin/python /Users/wen/PycharmProjects/test-scripts/main.py 
/Users/wen/PycharmProjects/test-scripts/venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
warnings.warn(
Traceback (most recent call last):
File "/Users/wen/PycharmProjects/test-scripts/venv/lib/python3.9/site-packages/appwrite/client.py", line 100, in call
response.raise_for_status()
File …
```

Filename should not be optional

---

templates/android/library/build.gradle.twig
tests/Android14Java11Test.php
tests/Android14Java8Test.php

- Upgrade OKhttp library version in Android SDK
- Existing tests
- https://github.com/appwrite/sdk-for-android/issues/42
YES

upgrade okhttp in android sdk

---

templates/ruby/lib/container/models/model.rb.twig

The generated model references map['data'], which is not defined because 'data' is not passed in from the API.
Instead, the API passes in user-defined attribute at the same level as system attributes that start with `$`
See: https://github.com/appwrite/sdk-for-ruby/blob/dd56d3d4a0ff469ab19c7728ac4f508daa7b8d42/lib/appwrite/models/document.rb#L39C1-L40C1
This fixes the issue by dynamically creating this `data` map from the `map` directly.

Fix Ruby not mapping document data properly

---

templates/dart/lib/src/models/model.dart.twig

- Handle required arrays that can be null during serialization in Dart and Flutter
- Generated and tested manually
- Fixes https://github.com/appwrite/sdk-for-flutter/issues/173
YES

fix required array in dart serialization

---

templates/dotnet/src/Appwrite/Client.cs.twig

Corrects the byte array check in the .NET SDK to prevent GetFileDownload/Preview/View functions from returning null values
- Generate new .NET SDK
- Verify correctly generated code in `Call()` function in `Client.cs`
- Use newly generated .NET SDK with the following C# code
```cs
using Appwrite;
using Appwrite.Services;
var client = new Client();
client
.SetEndpoint("http://cloud.appwrite.io/v1")
.SetProject("[PROJECT_ID]")
.SetKey("[API_KEY]");
var storage = new Storage(client);
var download = await storage.GetFileDownload("[BUCKET_ID]t", "[FILE_ID]");
File.WriteAllBytes($"output-{Guid.NewGuid()}.png", download);
```
No
Yes

Fix: byte array check to fix GetFileDownload function in .NET SDK

---

templates/cli/lib/commands/deploy.js.twig

remoteVariables was undefined so use total instead and make it match how it's done for wiping attributes and indexes.
Fixes: https://github.com/appwrite/sdk-for-cli/issues/112
Manually created SDK and deployed:
variable was successfully recreated:
None
Yes

Fix CLI deploy function

---

src/SDK/Language/DotNet.php
templates/dotnet/src/Appwrite/Converters/ValueClassConverter.cs.twig
templates/dotnet/src/Appwrite/Models/Model.cs.twig

Fix dotnet model collisions

---

templates/dart/base/utils.twig
templates/flutter/base/utils.twig

- uses the `enum.value` on enums for body params
- use `enum?.value` on optional enum params
- n/a
✅

fix: enum usage for body params

---

templates/apple/Sources/Client.swift.twig
templates/swift/Sources/Client.swift.twig
templates/swift/Sources/DeviceInfo/OSDeviceInfo.swift
templates/swift/Sources/DeviceInfo/iOS/IOSDeviceInfo.swift
templates/swift/Sources/DeviceInfo/iOS/UIDevice+ModelName.swift
templates/swift/Sources/OAuth/View+OAuth.swift.twig
templates/swift/Sources/OAuth/WebAuthComponent.swift.twig
templates/swift/Sources/PackageInfo/OSPackageInfo.swift
templates/swift/Sources/WebSockets/WebSocketClient.swift.twig
templates/swift/example-swiftui/Shared/ExampleView.swift
templates/swift/example-swiftui/Shared/Image/OSImage.swift

Add support for visionOS and arm64 simulator
Fix warnings:
1. use singleton instead of createNew
2. explicit ignore unused result
3. warning regarding sendable function closure
Fix error: WebAuthComponents was missing for swift-server target

Add support for vision os and fix warnings & errors

---

example.php
templates/cli/lib/commands/generic.js.twig
templates/cli/lib/questions.js.twig

Accounts with MFA enabled cannot signing using `appwrite login` (they can, but cannot do any actions)
TOTP sign in:
Sessison object:
Recovery code sign-in:
* https://github.com/appwrite/sdk-for-cli/issues/122
Yes

Feat: MFA support for CLI

---

templates/android/library/src/main/java/io/package/services/Realtime.kt.twig

Fixes Android realtime socket cleanup - last subscription was always active even after unsubscribing. 
Inspecting network, simple breakpoint in onMessage function and observing realtime count indicator in Appwrite dashboard revealed that realtime connection is still active and data is coming through even after disconnecting.
After the fix, socket is closed properly and Appwrite dashboard confirms it as well.
Similar issue found on sdk-for-web -> https://github.com/appwrite/sdk-generator/pull/809
Yes

Close Android realtime socket properly on unsubscribe

---

templates/swift/Sources/Services/Realtime.swift.twig
templates/swift/Sources/WebSockets/WebSocketClient.swift.twig

Fixes Apple realtime socket closing and cleanup - all subscription remained active all the time and closing socket never worked.
Inspecting network, simple breakpoint in onMessage function and observing realtime count indicator in Appwrite dashboard revealed that realtime connection is still active and data is coming through even after disconnecting.
Whats more, if realtime subscription is called multiple times during the lifecycle of the app, all subscription were active and were never cleared properly.
Similar issue found on sdk-for-web -> https://github.com/appwrite/sdk-generator/pull/809
and in sdk-for-android -> https://github.com/appwrite/sdk-generator/pull/814
Yes

Fix apple realtime socket cleanup

---

templates/dotnet/src/Appwrite/Client.cs.twig

The DotNet SDK has a bug where the SDK throws an InvalidOperationException if the "Content-Type" header is not present in the response from Appwrite. This is the case if you for example delete a document.
This PR changes the code to use `TryGetValues` which returns a boolean if it could successfully parse the header.
Fixes #805 
I checked out the repository of the dotnet-sdk, made the proposed changes and tested.
* #805 
I read the Contributing Guidelines

fix-805-change-GetValues-to-TryGetValues-when-parsing-content-type-header

---

templates/web/src/client.ts.twig

If the cookie fallback isn't set in local storage, the X-Fallback-Cookies header is set to empty even if the default header has some value set. This change will only set the header if there's a value in local storage to allow developer to set the fallback header if they have a value from somewhere else.
Fixes https://github.com/appwrite/sdk-for-web/issues/64
TBD
* https://github.com/appwrite/sdk-for-web/issues/64
Yes

Prevent clearing fallback header in Web SDK

---

templates/flutter/lib/src/realtime_mixin.dart.twig

Since subscription.close() modifies _subscriptions, we need to create a separate list to avoid concurrent modification error.
Closes https://github.com/appwrite/sdk-for-flutter/issues/200
Manually tested and confirmed subscribing and unsubscribing still works:
* https://github.com/appwrite/sdk-for-flutter/issues/200
Yes

Fix concurrent modification error when closing socket

---

templates/web/package.json.twig
templates/web/rollup.config.js.twig
templates/web/src/client.ts.twig

Removes `cross-fetch` and `isomorphic-form-data` from web SDK
Related Issues:
* https://github.com/vercel/next.js/issues/60687#issuecomment-1993484474
* https://github.com/appwrite/sdk-for-web/issues/85
* https://github.com/appwrite/sdk-for-web/issues/82
* https://github.com/appwrite/sdk-for-web/issues/53

chore: remove cross-fetch and isomorphic-form-data

---

src/SDK/Language/CLI.php
templates/cli/lib/commands/init.js.twig
templates/cli/lib/id.js.twig

Use function ID for the folder name so that:
1. it's more consistent with the rest of Appwrite
2. the function name can have special characters that cause problems for folders

Fix: CLI folder name (functions)

---

templates/apple/Package.swift.twig
templates/swift/Sources/Models/RealtimeModels.swift.twig
templates/swift/Sources/Services/Realtime.swift.twig
templates/swift/Sources/WebSockets/WebSocketClient.swift.twig
templates/swift/example-swiftui/Shared/ExampleView.swift
templates/swift/example-swiftui/Shared/ExampleViewModel.swift
tests/languages/apple/Tests.swift

- **BREAKING CHANGE**: `Realtime.subscribe` is now async
- Fixes https://github.com/appwrite/sdk-for-apple/issues/55
- Fixes https://github.com/appwrite/sdk-for-apple/issues/56
TBD
* https://github.com/appwrite/sdk-for-apple/issues/55
* https://github.com/appwrite/sdk-for-apple/issues/56
Yes

Fix Apple realtime with multiple subscriptions

---

templates/cli/lib/commands/deploy.js.twig

Renaming the `teamUpdate` function name in deployment to the [updated](https://github.com/appwrite/appwrite/pull/5196)  `teamUpdateName` one 
Locally against `1.5.5` instance
N/A
Yes

fix: renaming teamUpdate function the refactored one

---

templates/cli/lib/commands/push.js.twig

Keeping the `deploy` command available for `push` actions.
Other commands can't have backwards-compatibility, as they are in use for new things (`init` for exampe)

chore(cli): Allowing the use of `deploy` like `push`

---

templates/cli/lib/commands/pull.js.twig
templates/cli/lib/commands/push.js.twig

Changing command from singular to plural, for example: `appwrite pull collection` to `appwrite pull collections` .
CommanderJS will show errors like this automatically
```sh
error: unknown command 'collection'
(Did you mean collections?)
```
The change doesn't include `appwrite init` as this action is singular.

refactor(cli): Changing commands from singular to plural when applicable

---

templates/cli/lib/commands/init.js.twig
templates/cli/lib/questions.js.twig

- Refactor the function starter template from [function-starter](https://github.com/appwrite/functions-starter) to [templates](https://github.com/appwrite/templates).
- Adds the option to choose from many available templates.
Java doesn't have any templates other than the `starter` one, so it will be chosen by default
https://github.com/appwrite/sdk-generator/assets/316103/9133b0ee-509c-4296-959b-2ac2cc9f3594

feat(cli): Creating function from all available templates

---

templates/cli/lib/commands/pull.js.twig
templates/cli/lib/commands/push.js.twig
templates/cli/lib/config.js.twig

Adds the option to pull and project settings to be stored in the `appwrite.json` file, those settings are available to manage:
- Project services status (functions, account, etc.)
- Auth security settings (Session duration, User limit, etc.)
- Auth login methods (JWT, Phone, etc.)
https://github.com/appwrite/sdk-generator/assets/316103/fc089518-cf12-400a-b4f9-c383b1f99fb9

Enanched project settings CLI managment

---

templates/cli/index.js.twig
templates/cli/lib/parser.js.twig
templates/cli/lib/questions.js.twig
templates/cli/package.json.twig

The use of raw args gives the complete command

refactor: Improve command line to use `rawArgs`

---

templates/cli/lib/commands/push.js.twig
templates/cli/lib/questions.js.twig

- Shows table in any case, but wait for confirmation only when deleting/recreating
- Shows a note for when deleting or recreating
- Making sure `min` and `max` are numbers

Feat collection push improvements

---

example.php
templates/cli/index.js.twig
templates/cli/lib/commands/generic.js.twig
templates/cli/lib/commands/init.js.twig
templates/cli/lib/commands/run.js.twig
templates/cli/lib/config.js.twig
templates/cli/lib/emulation/docker.js.twig
templates/cli/lib/emulation/utils.js.twig
templates/cli/lib/parser.js.twig
templates/cli/lib/questions.js.twig

Feat cli g2 fixes

---

templates/swift/Sources/OAuth/WebAuthComponent.swift.twig

Avoid unnecessary crashes due to unrelated incoming URLs by:
- guard against existence of URL components.
- guard against query parameters
- validate required cookies *bonus: discard result from user defaults synchronization.
Didn't see any unit test files, otherwise i'd add code coverage for them. Happy to do it if there is a testing scheme!
- Create sample project with appwrite sdk
- establish universal links
- apply `.registerOAuthHandler()` to root view.
- start firing deeplinks, which will crash on open.
Discord
https://discord.com/channels/564160730845151244/1252726652044050572
Most of it.  Followed PR naming, and added a issue on github.

Remove force unwrapping of incoming url parameters

---

templates/cli/lib/client.js.twig
templates/cli/lib/commands/push.js.twig

Due to the way JavaScript handles numbers, the standard JSON parser will convert the max PHP int, 9223372036854775807, to
9223372036854776000. However, this is problematic because the resulting number is an invalid int in PHP so the integer validation fails.
This PR ensures we use JSONbig to parse and stringify JSON in the CLI to retain the precision of the numbers.
Fixes https://github.com/appwrite/sdk-for-cli/issues/124
Manually pulled and pushed successfully
* https://github.com/appwrite/sdk-for-cli/issues/124
Yes

Use JSONbig to parse and stringify JSON

---

templates/cli/lib/sdks.js.twig

The command should be `init project` and not just `init` as `init` will create some resource in a project
Manual
None
Yes

Fix error when no project set

---

templates/cli/lib/config.js.twig

Keys were missing so they weren't stored in the appwrite.json. As such, they wouldn't be set when pushing.
Manual:
Result after pulling includes keys like min and max:
None
Yes

Ensure all attribute keys are pulled into appwrite.json

---

templates/cli/lib/commands/pull.js.twig

appwrite-cli@6.0.0-rc.3 is missing a brace which results in:
```
$ npx appwrite-cli@next
Need to install the following packages:
appwrite-cli@6.0.0-rc.3
Ok to proceed? (y) y
/Users/steven/.npm/_npx/dd4d371d4e547a11/node_modules/appwrite-cli/lib/commands/pull.js:311
SyntaxError: Unexpected end of input
at internalCompileFunction (node:internal/vm:128:18)
at wrapSafe (node:internal/modules/cjs/loader:1280:20)
at Module._compile (node:internal/modules/cjs/loader:1332:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
at Module.load (node:internal/modules/cjs/loader:1206:32)
at Module._load (node:internal/modules/cjs/loader:1022:12)
at Module.require (node:internal/modules/cjs/loader:1231:19)
at require (node:internal/modules/helpers:179:18)
at Object.<anonymous> …
```

fix(cli): add missing brace

---

templates/cli/lib/emulation/docker.js.twig

Removes APPWRITE_ENV as its not good use case to support it.
None
x
Yes

Chore: Remove APPWRITE_ENV

---

templates/cli/lib/config.js.twig

A mismatch in variable name caused the "settings is not defined" error. This updates the variable name to match the parameter passed in.
Manually modified the CLI locally:
None
Yes

Fix "settings is not defined" error

---

templates/cli/lib/commands/run.js.twig

Run function default settings will be to run **without** variables.
Changing from `appwrite run function --no-variables` to `appwrite run function --with-variables`

chore(cli): Reversing running with variable logic

---

templates/react-native/docs/example.md.twig
templates/web/docs/example.md.twig

This PR addresses an issue in the example templates for the Appwrite documentation where the console logging of API responses was incorrectly referencing the response variable instead of the result variable. This discrepancy could potentially confuse users following the examples.
Updated the console logging in the example templates for both the web and React Native clients to use the result variable consistently.
The original templates incorrectly used response in the console.log statement, which does not align with the variable naming conventions in the example code provided. By changing this to result, we ensure clarity and accuracy in the displayed examples.
This change aligns with the conventions observed throughout the documentation examples and improves the usability for developers …

Fix variable names and logging in web and react-native docs templates #8328 

---

templates/cli/lib/commands/push.js.twig
templates/cli/lib/config.js.twig
templates/cli/lib/questions.js.twig

- Fix typo
- Better array checking in resource compering
- Checking collection basic definition

Fix cli bugs

---

templates/cli/base/params.twig

Making sure each function archive file has unique name

fix(cli): Bug when deploying multiple functions at once

---

templates/cli/lib/commands/pull.js.twig

Uses new method name from 1.6.x
x
Yes

Fix: Rename to use new method

---

templates/cli/lib/commands/push.js.twig

Removing vcs fields when deploying function so they will be empty
Locally
https://github.com/appwrite/appwrite/pull/8500

fix(cli): Removing VCS fields

---

templates/cli/lib/commands/push.js.twig

If both fields are "empty" we won't compere them for changes
👇 An example before and after the change

refactor(cli): skip empties when pushing

---

templates/cli/lib/commands/init.js.twig
templates/cli/lib/commands/pull.js.twig

When creating/pulling function it will placed in a folder named with the function's name

refactor(cli): use function name as destination folder

---

templates/flutter/lib/src/realtime_mixin.dart.twig

- Fixes Flutter realtime auto reconnect
- Catch internal websocket creation exceptions in `_createSocket`
- https://github.com/appwrite/sdk-for-flutter/issues/108
- https://github.com/appwrite/sdk-for-flutter/pull/212
YES

Fix Flutter realtime reconnection

---

src/SDK/Language/Go.php
templates/go/client.go.twig

- Handling upload of files smaller than the minimum chunk.
- Changing collection attributes to `[]map[string]any` aka dynamic object

Refactor go improvments

---

templates/ruby/lib/container/client.rb.twig

Ruby SDK had a bug where payload for create deployment looked like this:
```
------A30#3ad1
Content-Disposition: form-data; name="entrypoint"
index.rb
------A30#3ad1
Content-Disposition: form-data; name="code"; filename="index.rb"
Content-Type: application/x-ruby
require "appwrite"
def main(context)
return context.res.json(
{
"motto": "Build like a team of hundreds_",
"learn": "https://appwrite.io/docs",
"connect": "https://appwrite.io/discord",
"getInspired": "https://builtwith.appwrite.io",
}
)
end
------A30#3ad1--  <----- THIS IS A THE PROBLEM, `--` TERMINATES THE MULTIPART
Content-Disposition: form-data; name="activate"
true
------A30#3ad1
```

fix: ruby create deployment

---

composer.lock
templates/cli/lib/commands/push.js.twig
templates/cli/lib/config.js.twig

Pulls missing details when running `appwrite pull settings`. Also introducing push for those.
Before:
After:
Push:
x
x

Feat: Pull mock numbers and session alerts

---

templates/swift/Sources/Models/Model.swift.twig

Fix swift double optional caused by `?` added in both filter and template

Fix swift double optional

---

templates/android/library/src/main/java/io/package/services/Service.kt.twig

Before this, the `it.value.toString()` caused the list of scopes to be encoded like `scopes[]=[scope1, scope2]` which is invalid.
This change fixes the encoding to `scopes[]=scope1&scopes[]=scope2` as expected by the server.
Tested running this code:
```kotlin
fun main() {
val apiParams = mutableMapOf<String, Any?>(
"scopes" to listOf("user.read", "user.write"),
)
val apiQuery = mutableListOf<String>()
apiParams.forEach {
when (it.value) {
null -> {
return@forEach
}
is List<*> -> { 
(it.value as List<*>).forEach { v ->
apiQuery.add("${it.key}[]=${v.toString()}")
}
}
else -> {
apiQuery.add("${it.key}=${it.value.toString()}")
}
}
}
print(apiQuery)
}
```
in [Kotlin playground](https://play.kotlinlang.org/):
* https://github.com/appwrite/sdk-for-android/issues/60
Yes

fix(android): fix invalid encoding of scopes in query parameters

---

src/SDK/Language/Dart.php

- Fixes weird enum for `ExectuionMethod.pOST` in dart/flutter
Manually verified
YES

fix enum dart

---

templates/dotnet/Package/Client.cs.twig

closes #963 
Manually on several files in all sizes

fix(dotnet): chunk upload

---

templates/web/src/client.ts.twig

Adds `credentials: 'include'` to fetch options ensure 3rd party cookies are sent

fix(web): credentials include

---

templates/cli/lib/emulation/utils.js.twig
templates/cli/lib/questions.js.twig

- Applies proper build command for starters used in Appwrite CLI
- Uses proper command to start Deno during local devleopment
Before:
AFter:
x
Yes

Fix: Deno commands

---

templates/cli/lib/emulation/utils.js.twig

In Python, we switched from Flask to asynciohttp library.
With that, start command changed. CLI has start-command hard-coded, so we need to update it.
What I did instead is used helper bash script. This resolves the problem, and also ensures it doesn't happen in future. Those start helpers are what Open Runtimes tests use, so they are always 100% reliable.
I only manually tested everything working properly with Python and Node, but start helper is used for all runtime tests in Open Runtimes, so it gives me confidence it's not breaking anything currently working fine.
Before:
After:
- Discord discussion: https://discord.com/channels/564160730845151244/1297382564515942470
Yes

Fix: container start commands

---

src/SDK/Language/CLI.php
src/SDK/Language/Dart.php
src/SDK/Language/Deno.php
src/SDK/Language/DotNet.php
src/SDK/Language/Go.php
src/SDK/Language/JS.php
src/SDK/Language/Kotlin.php
src/SDK/Language/Node.php
src/SDK/Language/ReactNative.php
src/SDK/Language/Swift.php
src/SDK/Language/Web.php

Currently response model classes don't use the nested type for list types. This PR fixes that.
E.g. for Kotlin `Document.permissions` is currently `List<Any>`, when it should be `List<String>`

Fix model array subtypes

---

templates/android/library/src/main/java/io/package/services/Realtime.kt.twig
templates/flutter/lib/src/realtime_mixin.dart.twig
templates/swift/Sources/Services/Realtime.swift.twig

- Add realtime connection heartbeat
- Adds ping/pong heartbeat mechanism to maintain realtime connections on Android, Flutter, and Swift platforms. 
- Sends ping every 20s and handles cleanup.

feat: realtime heartbeat

---

templates/apple/base/requests/oauth.twig
templates/swift/Sources/OAuth/WebAuthComponent.swift.twig

This PR aads support for showing an InApp Safari ViewController or Apple's SignIn Native prompt [whichever is supported] instead of opening Safari externally.
Manual.
N/A.
Yes.

Feat: In-App OAuth2 Sign-in

---

templates/cli/lib/commands/push.js.twig

Scopes were not added to the functions on initial `appwrite push function`. This PR fixes that.

Fix: Scopes not pushed on function creation

---

templates/python/docs/example.md.twig

It looks like when we https://github.com/appwrite/sdk-generator/pull/700, we accidentally [deleted that import](https://github.com/appwrite/sdk-generator/commit/c6b568620a09c138ea82fcddc01880ce07cb3f6e#diff-5e6917afab7f018468629a5c5a64c13536c4a85f50e0af6b46304258c49e391c).
Fixes https://github.com/appwrite/sdk-for-python/issues/84
Manually generated and inspected examples:
* https://github.com/appwrite/sdk-for-python/issues/84
* https://github.com/appwrite/sdk-generator/pull/700
Yes

Add missing service import for Python examples

---

templates/dart/lib/src/models/model.dart.twig

Fixes a type error where `List<dynamic>` was not properly converted to `List<String>` in generated model classes. The issue occurred because array elements weren't being explicitly converted to their target type. Added proper type conversion and null safety handling for array deserialization.
Related:
* https://github.com/appwrite/appwrite/issues/9119

fix: cast string arrays

---

templates/cli/lib/commands/init.js.twig
templates/cli/lib/commands/push.js.twig
templates/cli/lib/config.js.twig
templates/cli/lib/questions.js.twig

This PR adds support for specifications into the CLI.
Test manually if everything is working as expected
Yes

Add specifications support to CLI

---

templates/cli/lib/commands/push.js.twig

This PR adds specification to a section of `push.js` in the CLI that updates functions so you can edit the appwrite.json file and change specs.
Test that updating a specification from the CLI is possible manually
Yes

Fix: Add missing specification in CLI

---

templates/python/package/client.py.twig

Fixes an issue with the final chunk upload calculation when using byte-based file sources. Changes the end index of the last chunk from `size - offset` to `size` to ensure all remaining bytes are included. 
Related:
* https://github.com/appwrite/sdk-for-python/issues/100

fix: python chunked upload

---

templates/android/library/src/main/java/io/package/models/RealtimeModels.kt.twig
templates/android/library/src/main/java/io/package/services/Realtime.kt.twig
templates/flutter/lib/src/realtime_response.dart.twig
templates/react-native/src/client.ts.twig
templates/swift/Sources/Services/Realtime.swift.twig
templates/web/src/client.ts.twig

During creation of heartbeat messages in realtime, the response is `{"type": "pong"}`. It does not contain the `data` attribute that the code does not account for, leading to error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'
```
This PR adds null-safety checks for message event type in flutter, android, ios, web and react-native. it also makes accounting for `pong` type consistent.
* https://github.com/appwrite/sdk-generator/issues/1026
Yes.

fix: added null checks for message.data & pong type checking

---

templates/web/src/services/template.ts.twig

Currently the sdk-generator adds the following twice in some scenarios -
`payload['project'] = this.client.config.project;`

fix(web): duped auth config

---

templates/dart/lib/src/models/model.dart.twig
templates/dotnet/Package/Models/Model.cs.twig

- **fix(dotnet): models formatting**
- **fix(dart): models empty sub_schema array scenario**

fix: dotnet & dart models

---

composer.lock
src/Spec/Swagger2.php
templates/android/library/src/main/java/io/package/services/Service.kt.twig
templates/apple/Sources/Services/Service.swift.twig
templates/dart/lib/services/service.dart.twig
templates/deno/src/services/service.ts.twig
templates/dotnet/Package/Services/ServiceTemplate.cs.twig
templates/flutter/lib/services/service.dart.twig
templates/kotlin/src/main/kotlin/io/appwrite/services/ServiceTemplate.kt.twig
templates/node/src/services/template.ts.twig
templates/php/docs/service.md.twig
templates/php/src/Services/Service.php.twig
templates/python/package/services/service.py.twig
templates/react-native/src/services/template.ts.twig
templates/swift/Sources/Services/Service.swift.twig
templates/web/src/services/template.ts.twig

This PR implements route multiplexing for supporting multiple methods being created from one API.
Yes

Implement SDK Method Multiplexing

---

CONTRIBUTING.md
src/SDK/Language/Node.php
src/SDK/Language/Web.php

In our swagger specs, we have defined the typings for an attribute to be attributeBoolean, attributeInteger and so on... but in SDK generator although we have the typings defined, we default `attribute`'s typing to an array of strings instead of using the defined typings.
This PR adds check if typings exist in "anyOf" field of the spec, and use those as a union.
Before:
```
attribute: string[]
```
After:
```
attributes: (Models.AttributeBoolean | Models.AttributeInteger | Models.AttributeFloat | Models.AttributeEmail | Models.AttributeEnum | Models.AttributeUrl | Models.AttributeIp | Models.AttributeDatetime | Models.AttributeRelationship | Models.AttributeString)[];
```
- https://github.com/appwrite/sdk-for-node/issues/87
Yes.

Fix "attributes" typing for Node and Web SDKs

---

templates/node/src/services/template.ts.twig
templates/react-native/src/services/template.ts.twig
templates/web/src/services/template.ts.twig

Solves issue #1035 
#1035 
yes

removed returning await pattern from node templates

---

templates/dart/lib/src/client_base.dart.twig
templates/dart/lib/src/client_browser.dart.twig
templates/dart/lib/src/client_io.dart.twig
templates/flutter/lib/src/client_base.dart.twig
templates/flutter/lib/src/client_browser.dart.twig
templates/flutter/lib/src/client_io.dart.twig

Use base class on dart/flutter for `ping`

---

src/SDK/Language/Web.php
templates/node/src/services/template.ts.twig
templates/web/src/services/template.ts.twig

1. fix spacing in sdk for web (there was one extra in front of method names).
2. remove unnecessary async in sdk for node.
3. make the return for `webAuth` be string or void instead of promise. this previously did not give an error since methods were async.
4. remove unnecessary adding of payload in web auth. it would just add project in the payload, which would already be added in headers:
yes.

chore: remove unnecessary async and spacing

---

.github/workflows/tests.yml
src/SDK/Language/Python.php
templates/python/package/services/service.py.twig
tests/Python313Test.php

In Python 3.13, list is now treated strictly as a built-in function, not a generic type hint. Python 3.13 introduces stricter type enforcement, causing conflicts when `list[str]` is used without `from typing import List`. Hence we get this error
```
Traceback (most recent call last):
File "/Users/christyjacob/opensource/christyjacob4/mcp-server-appwrite/.venv/bin/mcp-server-appwrite", line 4, in <module>
from mcp_server_appwrite.__main__ import main
File "/Users/christyjacob/opensource/christyjacob4/mcp-server-appwrite/src/mcp_server_appwrite/__init__.py", line 1, in <module>
from . import server
File "/Users/christyjacob/opensource/christyjacob4/mcp-server-appwrite/src/mcp_server_appwrite/server.py", line 11, in <module>
from appwrite.services.databases import Databases
File …
```

fix: add typing module for python 3.13

---

templates/react-native/src/services/template.ts.twig

Only methods with type "upload", i.e `createFile` in storage, and `createDeployment` in functions need async signature.
Yes.

chore: remove unnecessary async calls in react-native

---

templates/node/src/client.ts.twig
templates/react-native/src/client.ts.twig
templates/web/src/client.ts.twig

A response stream can only be read once. That's why reading it for text and then reading it again for json gave error "Already read". The error was caught and fixed in web and node, but left in react-native. This PR makes the logic consistent across all three.
* https://github.com/appwrite/sdk-for-react-native/issues/49
* https://github.com/appwrite/sdk-for-react-native/issues/50
Yes.

fix: appwrite exception already read

---

example.php
templates/python/package/services/service.py.twig

Adds improved docstrings to python sdk.
for multi strings:
Yes.

chore: improve docstrings for python

---

templates/python/package/services/service.py.twig

Updates response types for python.
Yes.

chore: update response types for python

---

templates/cli/lib/utils.js.twig

In python-ml function, we copy over files to `runtime-env` here - https://github.com/open-runtimes/open-runtimes/blob/088ef387b097cc7bb29aff6602372ac1196c5925/runtimes/python/versions/latest/helpers/prepare-start.sh#L4
This folder contains various files, even including symlinks.
Symlinks when copied over won't be valid files anymore and hence the `getAllFiles` function in CLI throws an error trying to fetch absolute paths for it.
So the PR makes the function just skip any invalid symlinks.
Before:
After:
- https://github.com/appwrite/sdk-for-cli/issues/150
Yes.

fix: hot swapping error in python ml function

---

templates/android/.github/workflows/stale.yml
templates/apple/.github/workflows/stale.yml
templates/cli/.github/workflows/stale.yml
templates/dart/.github/workflows/stale.yml
templates/deno/.github/workflows/stale.yml
templates/dotnet/.github/workflows/stale.yml
templates/flutter/.github/workflows/stale.yml
templates/go/.github/workflows/stale.yml
templates/graphql/.github/workflows/stale.yml
templates/kotlin/.github/workflows/stale.yml
templates/node/.github/workflows/stale.yml
templates/php/.github/workflows/stale.yml
templates/python/.github/workflows/stale.yml
templates/react-native/.github/workflows/stale.yml
templates/rest/.github/workflows/stale.yml
templates/ruby/.github/workflows/stale.yml
templates/swift/.github/workflows/stale.yml
templates/web/.github/workflows/stale.yml

Stale workflow

---

example.php
templates/android/library/src/main/java/io/package/services/Service.kt.twig
templates/dotnet/Package/Client.cs.twig
templates/kotlin/src/main/kotlin/io/appwrite/services/ServiceTemplate.kt.twig
tests/resources/spec.json

For android and kotlin, before apiHeaders always contained a value. But due to recent change in specs, we now removed unnecessary header for content type in GET and HEAD methods. This lead to apiHeaders being blank, leading to build errors - 
The PR fixes this with explicit typing.
Yes.

fix: inference error for apiHeaders

---

example.php
src/SDK/SDK.php
src/Spec/Spec.php
src/Spec/Swagger2.php
templates/android/docs/java/example.md.twig
templates/android/docs/kotlin/example.md.twig
templates/android/example/src/main/java/io/package/android/utils/Client.kt.twig
templates/dart/docs/example.md.twig
templates/deno/docs/example.md.twig
templates/dotnet/docs/example.md.twig
templates/flutter/docs/example.md.twig
templates/go/docs/example.md.twig
templates/kotlin/docs/java/example.md.twig
templates/kotlin/docs/kotlin/example.md.twig
templates/node/docs/example.md.twig
templates/php/docs/example.md.twig
templates/python/docs/example.md.twig
templates/react-native/docs/example.md.twig
templates/ruby/docs/example.md.twig
templates/swift/docs/example.md.twig
templates/web/docs/example.md.twig

Introduces new endpoint just for docs / examples that will have `<REGION>` in it.
yes.

feat: endpoint for docs / examples

---

templates/dart/lib/src/client_mixin.dart.twig
templates/flutter/lib/src/client_mixin.dart.twig

Only encodes user-agent header if its set. Previously it would have set a empty string as user-agent which browsers like safari did not like.
Yes.

chore: only encode user-agent if set

---

templates/react-native/package.json.twig

Resolves the "PlatformConstants could not be found" invariant violation that occurs when using React Native SDK with Expo 53. Updates all necessary dependencies to ensure compatibility with the new Expo version.
- https://github.com/appwrite/sdk-for-react-native/issues/45
yes.

fix: bump dependencies to resolve PlatformConstants error with Expo 53

---

templates/cli/lib/commands/generic.js.twig

Because the error function was shadowed by the caught error, you'd see an error like:
Error: error is not a function
This prevents the error function from being shadowed so that it is still callable.
Tested manually
Before:
After:
None
Yes

fix(cli): prevent shadowed error function

---

templates/cli/lib/client.js.twig

Prior to this change, the CLI would replace the cookies in the config if the server returned any cookies, even when not authenticating.
This change makes it so we check for the Appwrite session cookie and only save that cookie if it's found in the response.
This was happening when I was using the CLI against a codespaces instance I had. So, I manually tweaked the code and then successfully connected to the codespace without losing the session:
None
Yes

fix(cli): prevent session cookie from being wiped

---

templates/apple/Sources/Client.swift.twig
templates/swift/Sources/Client.swift.twig

`CharacterSet.urlHostAllowed` contains the `+` symbol as allowed, leading to it not being encoded and errors in requests that contain it, specifically time based requests in Queries:
https://stackoverflow.com/questions/41561853/couldnt-encode-plus-character-in-url-swift 
The PR as the stack overflow thread suggests encodes the `+` symbol separately.
- https://github.com/appwrite/sdk-for-apple/issues/72
yes.

fix: encode + in parametersToQueryString

---

templates/flutter/lib/src/client_browser.dart.twig
templates/flutter/lib/src/client_io.dart.twig
templates/flutter/pubspec.yaml.twig

Migration guide followed - https://pub.dev/packages/flutter_web_auth_2#upgrading-to-4x
For now we are keeping the old behaviour and disabling usage of `webView` for linux and windows platforms. But in future we can introduce an option to enable it.
- https://github.com/appwrite/sdk-generator/issues/1064
- https://github.com/appwrite/sdk-for-flutter/issues/238
- https://github.com/appwrite/appwrite/pull/9858
yes.

chore: update flutter_web_auth_2 to 4.x

---

templates/node/src/client.ts.twig
templates/web/src/client.ts.twig

Site and functions got `createDeployment` that have param called `code`, not `file`. This makes param dynamic, so it works properly for those scenarios. Until now it only worked well for Storage.
https://github.com/appwrite/console/pull/1888
https://discord.com/channels/564160730845151244/1375865210279166113
Yes

Fix: file deployment for functions and sites

---

templates/flutter/lib/src/client_browser.dart.twig

Fixes devKeys support in flutter.
When devKeys is set, we treat the authentication method as "keys" based, and thus we should not include "credentials: include". This change was also implemented in web and react native, was left in flutter.
the following error is thrown otherwise:
yes.

fix: devKeys support in flutter by conditionally including credentials

---

example.php
src/SDK/SDK.php

exclude assistant service in cli as its not needed there.
yes.

chore: exclude assistant service in cli

---

templates/cli/lib/type-generation/languages/dart.js.twig
templates/cli/lib/type-generation/languages/java.js.twig
templates/cli/lib/type-generation/languages/javascript.js.twig
templates/cli/lib/type-generation/languages/kotlin.js.twig
templates/cli/lib/type-generation/languages/php.js.twig
templates/cli/lib/type-generation/languages/swift.js.twig
templates/cli/lib/type-generation/languages/typescript.js.twig

We should not be automatically converting user defined keys to camel case, and instead keep them as it is.
also avoids escapting of HTML characters by replacing `<%=` with `<%-`.
before:
after:
yes.

fix: remove conversion of attribute keys to camel case

---

templates/cli/lib/type-generation/languages/dart.js.twig
templates/cli/lib/type-generation/languages/java.js.twig
templates/cli/lib/type-generation/languages/javascript.js.twig
templates/cli/lib/type-generation/languages/kotlin.js.twig
templates/cli/lib/type-generation/languages/php.js.twig
templates/cli/lib/type-generation/languages/swift.js.twig
templates/cli/lib/type-generation/languages/typescript.js.twig

reverts removal of camel casing, also fixes casing for enums:
yes.

revert: remove conversion of attribute keys to camel case

---

src/SDK/Language/CLI.php
templates/cli/CHANGELOG.md.twig
templates/cli/lib/commands/generic.js.twig
templates/cli/lib/commands/init.js.twig
templates/cli/lib/commands/push.js.twig
templates/cli/lib/config.js.twig
templates/cli/lib/parser.js.twig
templates/cli/lib/questions.js.twig
templates/cli/lib/sdks.js.twig
templates/cli/lib/type-generation/attribute.js.twig
templates/cli/lib/type-generation/languages/dart.js.twig
templates/cli/lib/utils.js.twig

1. fix unsupported attribute error.
2. fix duplication of error messages:
3. fix strict comparision of floating points: `min changed from -1.7976931348623157e+308 to -1.7976931348623157e+308`
1. <img width="584" alt="Screenshot 2025-06-23 at 9 11 44 AM" src="https://github.com/user-attachments/assets/367dda46-8956-4266-9461-5aa1daeb599f" />
---
2. <img width="858" alt="Screenshot 2025-06-23 at 9 12 04 AM" src="https://github.com/user-attachments/assets/dcbce5ae-41ef-4bb0-8cd9-deebac6731d1" />
yes.

fix: add unsupported attribute error

---

templates/apple/Sources/Services/Service.swift.twig
templates/swift/Sources/Services/Service.swift.twig

uses swift-native doc comments instead of jsdoc styled comments for apple and swift sdks.
uses this doc as the reference from official swift repository - https://github.com/swiftlang/swift/blob/main/docs/DocumentationComments.md
before:
after:
yes.

chore: use swift-native doc comments

---

src/SDK/Language/Node.php
src/SDK/Language/Web.php
templates/node/src/services/template.ts.twig
templates/web/src/models.ts.twig
templates/web/src/services/template.ts.twig

Fixes document typing by:
1. introducing default model and document without keys:
```ts
export type DefaultDocument = Document & {
[key: string]: any;
[__default]: true;
};
export type DataWithoutDocumentKeys = {
[K in string]: any;
} & {
[K in keyof Document]?: never;
};
```
2. Update document methods to use it:
```ts
data: Document extends Models.DefaultDocument ? Models.DataWithoutDocumentKeys : Omit<Document, keyof Models.Document>
```
- https://github.com/appwrite/sdk-for-web/issues/76
yes.

fix: update document type handling and improve generics in TS

---

templates/cli/lib/client.js.twig
templates/cli/lib/commands/command.js.twig

error that was caused:
fix:
1. remove warnings from methods as a warning from `client` call will be returned via header
2. switched using `console.warn` as that method does not exist in CLI
yes.

fix: deprecated warnings in cli leading to error

---

src/SDK/Language/Node.php
src/SDK/Language/Web.php
templates/react-native/src/models.ts.twig
templates/web/src/models.ts.twig

breakdown:
1. case 1 - generic is not passed, i.e `Document extends Models.DefaultDocument` satisfies. then:
```ts
Partial<Models.Document> & Record<string, any>
```
meaning allow internal attributes like `$id`, `$collectionId` etc. but "partially", meaning you get type completion but not 	required. apart from that allow any key.
**aka** allow any thing but get type completion on internal attributes
2. case 2 - generic is not passed, the condition fails and now it's `Document extends Models.Document = Models.DefaultDocument`. then it's:
```ts
Partial<Models.Document> & Omit<Document, keyof Models.Document>
```
meaning again allow type completion on internal attributes, but make keys of `Document` compulsory just omiting the internal attributes
for patch methods, we just wrap …

chore: allow internal attributes partially in web and node

---

templates/dotnet/base/utils.twig

Always send enum wrappers as string values in API parameters to prevent serialization issues.
generated sdk (1.7.x server)
In dart base/utils, there is a similar implementation for enum.
https://github.com/appwrite/sdk-for-dotnet/issues/54
assign me?
Yes

fix(.NET): pass enum value as string in API params

---

templates/node/src/services/template.ts.twig
templates/web/src/services/template.ts.twig

fixes this error:
we dont need to explicitly add `| undefined` since param is already marked with `?`
removing it solves the issue.
yes.

fix: type error on data in updateDocument method

---

example.php
templates/node/src/services/template.ts.twig
templates/react-native/src/services/template.ts.twig
templates/web/src/services/template.ts.twig

continuation of the other pr to implement object params in react native sdk as well
```ts
/**
* Get a list of all databases from the current Appwrite project. You can use the search parameter to filter your results.
*
* @param {string[]} queries - Array of query strings generated using the Query class provided by the SDK. [Learn more about queries](https://appwrite.io/docs/queries). Maximum of 100 queries are allowed, each 4096 characters long. You may filter on the following attributes: name
* @param {string} search - Search term to filter your list results. Max length: 256 chars.
* @throws {AppwriteException}
* @returns {Promise}
* @deprecated This API has been deprecated since 1.8.0. Please use `Grids.listDatabases` instead.
*/
list(params: { queries?: string[], search?: string  }): …
```

feat: object params in react native sdk

---

example.php
templates/cli/lib/client.js.twig
templates/cli/lib/commands/pull.js.twig
templates/cli/lib/commands/push.js.twig
templates/cli/lib/config.js.twig
templates/cli/lib/questions.js.twig

deprecate old methods and new tables methods
old one works with a warning:
```bash
cli git:(feat-tables-commands) ./build/appwrite-cli-darwin-arm64 pull
? Which resources would you like to pull? Collections (Database)
ℹ Warning: appwrite pull collection has been deprecated. Please consider using 'appwrite pull tables' instead
```
yes.

feat: introduce tables commands and deprecate collections commands

---

src/SDK/Language/Dart.php
src/SDK/Language/Flutter.php
templates/dart/base/requests/api.twig
templates/dart/base/requests/file.twig
templates/dart/base/requests/location.twig
templates/dart/base/requests/oauth.twig
templates/dart/lib/id.dart.twig
templates/dart/lib/package.dart.twig
templates/dart/lib/query.dart.twig
templates/dart/lib/role.dart.twig
templates/dart/lib/src/client.dart.twig
templates/dart/lib/src/client_stub.dart.twig
templates/dart/lib/src/upload_progress.dart.twig
templates/dart/test/query_test.dart.twig
templates/dart/test/src/enums_test.dart.twig
templates/dart/test/src/exception_test.dart.twig
templates/dart/test/src/input_file_test.dart.twig
templates/dart/test/src/models/model_test.dart.twig
templates/flutter/.github/workflows/test.yml
templates/flutter/lib/services/service.dart.twig
templates/flutter/lib/src/client.dart.twig
templates/flutter/lib/src/client_base.dart.twig
templates/flutter/lib/src/client_browser.dart.twig
templates/flutter/lib/src/client_io.dart.twig
templates/flutter/lib/src/client_mixin.dart.twig
templates/flutter/lib/src/client_stub.dart.twig
templates/flutter/lib/src/realtime_stub.dart.twig
templates/flutter/lib/src/realtime_subscription.dart.twig
templates/flutter/test/services/service_test.dart.twig
templates/flutter/test/src/realtime_response_connected_test.dart.twig

* chore(flutter): fix formatting issues
* chore(flutter): fix tests
Manually generated and ran tests:
* https://github.com/appwrite/sdk-generator/pull/1149
Yes

Chore improve flutter dart sdk scores

---

templates/cli/lib/client.js.twig

Provides a fix for https://github.com/appwrite/appwrite/issues/9042 causing project related CLI operations to not work (specifically on macOS and Windows for some reason)
I build and tested with an existing project. Where before I was getting the error "Project with the requested ID could not be found. Please check the value of the X-Appwrite-Project header to ensure the correct project ID is being used." I now do not.
https://github.com/appwrite/appwrite/issues/9042
Yes

(fix) double slash in path
