appwrite/sdk-generator

- src/SDK/Language/Deno.php
fixes https://github.com/appwrite/sdk-for-deno/issues/1
> fix(deno/array): set array type to any

- templates/flutter/pubspec.yaml.twig
updated dependencies to latest version
> updated dependencies

- templates/flutter/lib/client.dart.twig
With this PR I add web support. In this, I have not touched the part of oAuth yet. I will be exploring that later.
> Flutter Web support

- templates/flutter/lib/client.dart.twig
@eldadfux Just few changes adjusted for desktop. Best to publish a pre-release version and allow to test on desktop as well, before we ship
> modify origin header only if android/iOS

- templates/node/lib/client.js.twig
- templates/node/package.json.twig
+ Change request library from Requests to Axios
This is a PR in accordance to #33
> Switch from requests to axios

- CONTRIBUTING.md
Fixed a few typos and added numbers to creating lang class section making it more readable
> TYPO Correction

- src/SDK/Language/Java.php
- templates/java/docs/example.md.twig
Hi @eldadfux 
Please find PR for issue -> https://github.com/appwrite/sdk-generator/issues/42
Regards,
Nitin
> Added missing docs templates for Java

- src/SDK/Language/Dart.php
- templates/dart/docs/example.md.twig
- templates/dart/lib/client.dart.twig
- templates/dart/lib/package.dart.twig
- templates/dart/lib/services/service.dart.twig
- templates/dart/pubspec.yaml.twig
- tests/SDKTest.php
- tests/languages/dart/tests.dart
Hey,
- I have created Dart SDK templates,
- cleaned up Dart language file a bit with some fixes
- Removed Flutter specific and unused dependencies
Running into incorrect parameter type issue in functions api as mentioned here #76
> [Draft] Dart sdk

- tests/SDKTest.php
I've added test for Dart 2.12 beta. It did pass locally.
> Test for Dart 2.12 beta

- tests/SDKTest.php
- tests/languages/php/test.php
Added new upload tests to our tests suite. Only missing tests for Ruby and .NET
> Added upload tests

- tests/SDKTest.php
Updating SDKTest Whitelist array with Dart to run dart tests.
> Adding dart to test whitelist

- templates/dotnet/src/Appwrite/Client.cs.twig
- tests/SDKTest.php
- tests/languages/dotnet/tests.ps1
- fixes list processing with `multipart/form-data`
- adds upload test
> fix(dotnet): file upload

- src/SDK/Language/Ruby.php
- templates/ruby/Gemfile.twig
- templates/ruby/docs/example.md.twig
- templates/ruby/lib/container.rb.twig
- templates/ruby/lib/container/client.rb.twig
- templates/ruby/lib/container/file.rb.twig
- tests/SDKTest.php
- tests/languages/ruby/tests.rb
Hey,
This PR adds Upload support to Ruby SDK.
1. The build phase required ruby image instead of docker because of gemspec git dependency
2. The file content-type 'multipart/form-data' always assumes that a parameter named 'file' is there and is a valid path to a file
3. The binary content of the file is loaded in memory at once might not be suitable for large files at the moment
> Feature Ruby SDK upload support

- templates/cli/docs/example.md.twig
Removed extra spaces. Removed extra chars to allow easy copy/paste from Appwrite docs.
> Updated CLI examples

- templates/dart/pubspec.yaml.twig
- templates/flutter/lib/client.dart.twig
- templates/flutter/pubspec.yaml.twig
Updates and fixes to make work with latest Flutter and Dart and in desktop platforms.
> Fix flutter desktop with package info plus

- src/SDK/Language/Node.php
- src/SDK/Language/Typescript.php
- src/SDK/Language/Web.php
- templates/node/.travis.yml.twig
- templates/typescript/.travis.yml.twig
- templates/web/.travis.yml.twig
Added travis templates to allow us to automate NPM publishing.
> Added automated deployment to NPM

- src/SDK/Language/Flutter.php
Hey, looks like here again I made small mistake.
> Fix added missing file to the list

- example.php
- src/SDK/SDK.php
- templates/cli/README.md.twig
- templates/dart/README.md.twig
- templates/deno/README.md.twig
- templates/dotnet/README.md.twig
- templates/flutter/README.md.twig
- templates/go/README.md.twig
- templates/java/README.md.twig
- templates/node/README.md.twig
- templates/php/README.md.twig
- templates/python/README.md.twig
- templates/ruby/README.md.twig
- templates/swift/README.md.twig
- templates/typescript/README.md.twig
- templates/web/README.md.twig
Just a small update to the badges, really bothered me hehe....
> Added discord and twitter badges

- src/SDK/Language/CLI.php
- templates/cli/README.md.twig
- templates/cli/app/services/client.php.twig
- templates/cli/app/services/service.php.twig
- templates/cli/bin/client.twig
- templates/cli/bin/help.twig
- templates/cli/bin/init.twig
- templates/cli/bin/server.twig
- templates/cli/bin/service.twig
- templates/cli/bin/version.twig
- templates/cli/install.sh.twig
- templates/cli/src/Client.php.twig
Fix for following issues:
1. Added selfSign as a user preference
2. Fix sh: unknown operand 
3. Rename Services folder to services
> feat: fix cli issues

- templates/cli/app/services/client.php.twig
- templates/cli/app/services/init.php.twig
- templates/cli/app/services/service.php.twig
- Replace Mock() validator with Wildcard()
- Cast string to integer for body parameters.
> feat: added wildcard param to cli

- templates/cli/README.md.twig
- templates/cli/app/services/help.php.twig
- templates/cli/app/services/init.php.twig
- templates/cli/app/services/service.php.twig
- templates/cli/composer.json.twig
- templates/cli/docs/example.md.twig
- tests/SDKTest.php
- tests/languages/cli/test.php
- Support for new CLI array params
- Updated README and examples to use the new array syntax
> feat: added new array params

- templates/flutter/lib/client.dart.twig
- templates/flutter/lib/package.dart.twig
- templates/flutter/pubspec.yaml.twig
Resolves https://github.com/appwrite/appwrite/issues/946
Preview of how createSession responds with user device details on Android
> Flutter SDK Custom user agent

- templates/cli/install.ps1.twig
Missing line break didn't play well with PowerShell 👍🏻
> fix(cli): powershell installation

- templates/web/src/sdk.ts.twig
- fixes upper/lower case sensivity with `JWT`
> fix(web): case with JWT

- templates/web/src/sdk.ts.twig
- tests/languages/web/index.html
- tests/languages/web/node.js
- prevent parsing servers response with json, if there is no content.
- add 502 error test
> fix(web): conditional json parsing

- templates/web/src/sdk.ts.twig
- tests/SDKTest.php
- tests/languages/web/node.js
- tests/resources/spec.json
- adds the new spec
- fixes an exception for web
> tests(general): add new spec

- templates/cli/src/Client.php.twig
Fix for https://github.com/appwrite/appwrite/issues/1132
> feat: fix for unescaped space in strings

- templates/web/src/sdk.ts.twig
Before:
```ts
updateDocument: async <T extends unknown>(collectionId: string, documentId: string, data: object, read: string[] = [], write: string[] = []): Promise<T> => {
if (collectionId === undefined) {
throw new AppwriteException('Missing required parameter: "collectionId"');
}
if (documentId === undefined) {
throw new AppwriteException('Missing required parameter: "documentId"');
}
if (data === undefined) {
throw new AppwriteException('Missing required parameter: "data"');
}
let path = '/database/collections/{collectionId}/documents/{documentId}'.replace('{collectionId}', collectionId).replace('{documentId}', documentId);
let payload: Payload = {};
if (typeof data !== 'undefined') {
payload['data'] = data;
}
if (typeof read !== 'undefined') {
payload['read'] = read;
}
if (typeof …
```
> improve(web): param checking

- templates/ruby/lib/container/services/service.rb.twig
- add param checking
before:
```ruby
def update_document(collection_id:, document_id:, data:, read: [], write: [])
path = '/database/collections/{collectionId}/documents/{documentId}'
.gsub('{collectionId}', collection_id)
.gsub('{documentId}', document_id)
params = {
'data': data, 
'read': read, 
'write': write
}
return @client.call('patch', path, {
'content-type' => 'application/json',
}, params);
end
```
after:
```ruby
def update_document(collection_id, document_id, data, read = nil, write = nil)
if collection_id.nil?
raise Appwrite::Exception.new('Missing required parameter: "collectionId"')
end
if document_id.nil?
raise Appwrite::Exception.new('Missing required parameter: "documentId"')
end
if data.nil?
raise Appwrite::Exception.new('Missing required parameter: "data"')
end
path = …
```
> fix(ruby): overall improvements

- templates/python/package/services/service.py.twig
- add param checking
before:
```python
def update_document(self, collection_id, document_id, data, read=[], write=[]):
"""Update Document"""
params = {}
path = '/database/collections/{collectionId}/documents/{documentId}'
path = path.replace('{collectionId}', collection_id)                
path = path.replace('{documentId}', document_id)                
params['data'] = data
params['read'] = read
params['write'] = write
return self.client.call('patch', path, {
'content-type': 'application/json',
}, params)
```
after:
```python
def update_document(self, collection_id, document_id, data, read = None, write = None):
"""Update Document"""
if collection_id is None: 
raise AppwriteException('Missing required parameter: "collection_id"')
if document_id is None: 
raise AppwriteException('Missing …
```
> fix(python): overall improvements

- src/SDK/Language/Deno.php
- templates/deno/src/client.ts.twig
- templates/deno/src/exception.ts.twig
- templates/deno/src/services/service.ts.twig
- add param checking
- proper response type
before:
```typescript
async updateDocument(collectionId, documentId, data, read = [], write = []) {
let path = '/database/collections/{collectionId}/documents/{documentId}'.replace(new RegExp('{collectionId}', 'g'), collectionId).replace(new RegExp('{documentId}', 'g'), documentId);
return await this.client.call('patch', path, {
'content-type': 'application/json',
},
{
'data': data,
'read': read,
'write': write
});
}
```
after:
```typescript
async updateDocument<T extends unknown>(collectionId: string, documentId: string, data: object, read?: string[], write?: string[]): Promise<T> {
if (typeof collectionId === 'undefined') {
throw new AppwriteException('Missing required parameter: "collectionId"');
}
if (typeof documentId === 'undefined') { …
```
> fix(deno): overall improvements

- templates/node/lib/client.js.twig
@TorstenDittmann Hope this is correct here.
[Reference  1](https://github.com/appwrite/sdk-for-node/pull/15)
[Reference 2](https://github.com/appwrite/sdk-for-node/pull/14)
> Static flatten and Code Cleanup

- templates/android/docs/example.md.twig
Updated android kotlin examples
> feat: android example fixes

- templates/flutter/pubspec.yaml.twig
Fix for https://github.com/appwrite/appwrite/issues/1230
> Fix Windows Null Char issues

- templates/android/README.md.twig
- templates/android/example/src/main/java/io/appwrite/android/ui/accounts/AccountsFragment.kt.twig
- templates/android/library/build.gradle.twig
- templates/android/library/src/main/java/io/appwrite/Client.kt.twig
- templates/kotlin/README.md.twig
- templates/kotlin/docs/example.md.twig
- templates/kotlin/scripts/publish.gradle
- templates/kotlin/src/main/kotlin/io/appwrite/Client.kt.twig
* Fix Kotlin Docs
* Add maven central badges to android and kotlin README
* Change Staging repo URL
* Review Comments on Android
> feat: fix kotlin documentation

- templates/cli/app/services/service.php.twig
- templates/cli/install.sh.twig
Escape paths with spaces in the CLI :+1: 
Fixes : https://github.com/appwrite/sdk-for-cli/issues/10
> fix: cli path issue

- templates/flutter/lib/services/service.dart.twig
Fix: https://github.com/appwrite/appwrite/issues/1442
> fix flutter oauth completing too early

- templates/cli/install.ps1.twig
Add the cli container to the host network in windows
> feat(cli): add cli container to host network in powershell

- README.md
Add Android + Kotlin SDK's to readme
> Add Android + Kotlin SDK's to readme

- src/SDK/Language/Dart.php
- templates/flutter/lib/src/client_stub.dart.twig
- templates/flutter/lib/src/realtime_stub.dart.twig
> fix doc comments

- templates/flutter/lib/src/realtime_message.dart.twig
Fix realtime message timestamp
> fix timestamp

- templates/php/src/Services/Service.php.twig
- replaces `empty()` with `isset()` to support passing `false`
#244
> fix(php): null/false check

- templates/web/package.json.twig
- tests/SDKTest.php
- tests/languages/web/tests.js
- improve tests and version used
- updated to versions maintenance/stable/latest
> fix(tests): improve

- templates/flutter/docs/example.md.twig
- templates/flutter/lib/src/realtime_mixin.dart.twig
Fix realtime last url. When connection is closed, set it to null.
> fix realtime last url

- src/SDK/Language/Dart.php
- src/SDK/SDK.php
- templates/dart/lib/models.dart.twig
- templates/dart/lib/package.dart.twig
- templates/dart/lib/services/service.dart.twig
- templates/dart/lib/src/models/model.dart.twig
- tests/languages/dart/tests.dart
Response model support on Dart SDK
> Feat-dart-response-model

- src/SDK/Language.php
- src/SDK/Language/Dart.php
- src/SDK/Language/DotNet.php
- src/SDK/Language/Go.php
- src/SDK/Language/HTTP.php
- src/SDK/Language/JS.php
- src/SDK/Language/Kotlin.php
- src/SDK/Language/PHP.php
- src/SDK/Language/Python.php
- src/SDK/Language/Ruby.php
- src/SDK/Language/Swift.php
- src/SDK/SDK.php
- Allow language level overrides for specific identifiers
> Feat language level identifier overrides

- templates/flutter/lib/src/client_io.dart.twig
- templates/flutter/pubspec.yaml.twig
> flutter dependency upgrades

- templates/flutter/lib/src/realtime_mixin.dart.twig
from:
https://github.com/appwrite/sdk-for-flutter/pull/42
> bugfix double realtime connections

- src/SDK/Language/Dart.php
- templates/flutter/lib/services/service.dart.twig
- templates/flutter/lib/src/client_base.dart.twig
- templates/flutter/lib/src/client_browser.dart.twig
- templates/flutter/lib/src/client_io.dart.twig
- templates/flutter/lib/src/client_mixin.dart.twig
- templates/flutter/lib/src/cookie_manager.dart.twig
- templates/flutter/lib/src/exception.dart.twig
- templates/flutter/lib/src/realtime_base.dart.twig
- templates/flutter/lib/src/realtime_browser.dart.twig
- templates/flutter/lib/src/realtime_io.dart.twig
- templates/flutter/lib/src/realtime_mixin.dart.twig
- templates/flutter/pubspec.yaml.twig
> refactor: Add linting rules to flutter sdk, and change code to comply with the rules

- .gitignore
- templates/dart/lib/services/service.dart.twig
- templates/flutter/lib/services/service.dart.twig
- Removes regex from path string replace
- Updates .gitignore for local environment
> Removes RegEx from path building as it's not needed.

- templates/flutter/lib/src/client_browser.dart.twig
remove verification handled automatically by web
https://github.com/appwrite/sdk-for-flutter/issues/47
> fix flutter weboauth

- templates/android/library/src/main/java/io/appwrite/Query.kt.twig
- templates/dart/lib/query.dart.twig
- templates/deno/src/query.ts.twig
- templates/flutter/lib/query.dart.twig
- templates/kotlin/src/main/kotlin/io/appwrite/Query.kt.twig
- templates/node/lib/query.js.twig
- templates/php/src/Query.php.twig
- templates/python/package/query.py.twig
- templates/ruby/lib/container/query.rb.twig
- templates/swift/Sources/Models/Query.swift.twig
> Fix-remove-contains-query

- templates/deno/src/exception.ts.twig
- templates/flutter/pubspec.yaml.twig
- templates/ruby/gemspec.twig
- tests/languages/deno/tests.ts
- Update Flutter device_info_plus 3.2.0
- update ruby mime-types 3.4.1
> Feat-dependency-upgrades

- templates/node-cli/lib/commands/command.js.twig
> Implemenetd output path for file endpoints

- composer.lock
- templates/node/index.d.ts.twig
> Fix query class type definition

- templates/swift/README.md.twig
Closes https://github.com/appwrite/sdk-for-apple/issues/7
> Update package installation with Xcode for 13+

- templates/swift/Package.swift.twig
Closes https://github.com/appwrite/sdk-for-apple/issues/10
> Fix apple platform archive errors related to minimum deployment targets

- templates/flutter/lib/src/realtime.dart.twig
- templates/flutter/lib/src/realtime_mixin.dart.twig
- exposes the web-socket's close code so developers can check if connection is active
> Expose realtime websocket close code

- src/SDK/Language/Flutter.php
- templates/flutter/lib/package.dart.twig
- templates/flutter/lib/services/service.dart.twig
- templates/flutter/lib/src/chunked_upload_io.dart.twig
- templates/flutter/lib/src/chunked_upload_stub.dart.twig
- templates/flutter/lib/src/upload_progress.dart.twig
- tests/languages/flutter/tests.dart
Resumable upload support for Flutter
> resumable upload support on Flutter

- src/SDK/Language/Android.php
- src/SDK/Language/Kotlin.php
- src/SDK/Language/Swift.php
- templates/android/library/src/main/java/io/appwrite/Client.kt.twig
- templates/android/library/src/main/java/io/appwrite/models/Error.kt.twig
- templates/android/library/src/main/java/io/appwrite/models/UploadProgress.kt.twig
- templates/android/library/src/main/java/io/appwrite/services/ServiceTemplate.kt.twig
- templates/kotlin/src/main/kotlin/io/appwrite/Client.kt.twig
- templates/kotlin/src/main/kotlin/io/appwrite/models/UploadProgress.kt.twig
- templates/kotlin/src/main/kotlin/io/appwrite/services/ServiceTemplate.kt.twig
- templates/ruby/lib/container/client.rb.twig
- templates/swift/Sources/Client.swift.twig
- templates/swift/Sources/Models/UploadProgress.swift.twig
- templates/swift/Sources/Services/Service.swift.twig
- tests/KotlinTest.php
- tests/SwiftClientTest.php
- tests/SwiftServerTest.php
- tests/languages/kotlin/ServiceTest.kt
Use typed model for Android, Kotlin, Swift (Server + Client) and Ruby `upload` calls `onProgress` functional parameter
> Refactor on progress

- templates/python/package/client.py.twig
- templates/python/package/services/service.py.twig
Manual QA:
Generated code:
```
def chunked_upload(
self,
path,
headers = None,
params = None,
param_name = '',
on_progress = None,
):
file_path = str(params[param_name])
file_name = os.path.basename(file_path)
size = os.stat(file_path).st_size
if size < self._chunk_size:
slice = open(file_path, 'rb').read()
params[param_name] = InputFile(file_path, file_name, slice)
return self.call(
'post',
path,
headers,
params
)
input = open(file_path, 'rb')
offset = 0
counter = 0
if params['fileId'] != 'unique()':
try:
result = self.call('get', path + '/' + params['fileId'], headers)
counter = result['chunksUploaded']
except:
pass
if counter > 0:
offset = counter * self._chunk_size
input.seek(offset)
while offset < size:
slice = input.read(self._chunk_size) or input.read(size - offset) …
```
> Feat: Python resumable upload

- templates/deno/src/services/service.ts.twig
- tests/resources/spec.json
Showcase:
Generated function:
```
async createFile(bucketId: string, fileId: string, file: string, read?: string[], write?: string[], onProgress = (progress: UploadProgress) => {}): Promise<Models.File> {
if (typeof bucketId === 'undefined') {
throw new AppwriteException('Missing required parameter: "bucketId"');
}
if (typeof fileId === 'undefined') {
throw new AppwriteException('Missing required parameter: "fileId"');
}
if (typeof file === 'undefined') {
throw new AppwriteException('Missing required parameter: "file"');
}
let path = '/storage/buckets/{bucketId}/files'.replace('{bucketId}', bucketId);
let payload: Payload = {};
if (typeof fileId !== 'undefined') {
payload['fileId'] = fileId;
}
if (typeof file !== 'undefined') {
payload['file'] = file.toString();
}
if (typeof read !== …
```
> Feat: Deno resumable upload

- templates/cli/package.json.twig
- templates/flutter/pubspec.yaml.twig
- templates/node/package.json.twig
> upgrade flutter dependencies

- templates/swift/Sources/Client.swift.twig
- templates/swift/Sources/PackageInfo/Linux/PackageInfo+Linux.swift
- templates/swift/Sources/PackageInfo/Windows/PackageInfo+Windows.swift
- Fix swift/apple missing origin header
- Fix swift/apple  overriding global headers
> Swift/Apple Header Fixes

- templates/flutter/docs/example.md.twig
```dart
// generated code
import 'package:appwrite/appwrite.dart';
void main() { // Init SDK
Client client = Client();
Storage storage = Storage(client);
client
.setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
.setProject('5df5acd0d48c2') // Your project ID
;
// downloading file
Future result = storage.getFileDownload(
bucketId: '[BUCKET_ID]',
fileId: '[FILE_ID]',
).then((bytes) {
final file = File('path_to/file.pdf');
file.writeAsBytesSync(bytes)
}).catchError((error) {
print(error.response);
})
}
//displaying image preview
FutureBuilder(
future: storage.getFileDownload(
bucketId: '[BUCKET_ID]',
fileId: '[FILE_ID]',
), //works for both public file and private file, for private files you need to be logged in
builder: (context, snapshot) {
return snapshot.hasData && …
```
> Flutter file examples apart from image

- src/SDK/SDK.php
- Fix preg_replace/trim null subject deprecation warnings
> Fix deprecation warnings

- templates/swift/Sources/Models/Error.swift.twig
- tests/languages/swift-client/Tests.swift
- tests/languages/swift-server/Tests.swift
Related https://github.com/appwrite/appwrite/issues/3163
> Add extensions to allow propagating swift error message

- templates/android/library/src/main/java/io/appwrite/models/RealtimeModels.kt.twig
- templates/flutter/lib/src/realtime_message.dart.twig
- templates/swift/Sources/Models/RealtimeModels.swift.twig
- templates/swift/Sources/Services/Realtime.swift.twig
- templates/web/src/sdk.ts.twig
> Swift Client test is failing, since it checks against 0.13 Appwrite.
> fix: realtime event model for 0.14 events

- templates/cli/lib/questions.js.twig
New runtimes were released, so we are adding their entry points into CLI so it is automatically picked up.
> Feat: Add function runtimes to CLI

- templates/php/base/requests/api.twig
- templates/php/base/requests/file.twig
- templates/php/base/requests/params.twig
- templates/php/src/Services/Service.php.twig
> php template refactor

- templates/dart/lib/src/input_file.dart.twig
- templates/flutter/lib/src/input_file.dart.twig
- This change will allow easier instantiation of InputFile without checking platforms in their app
> Fix file type for easy cross-platform access

- templates/flutter/pubspec.yaml.twig
- templates/python/requirements.txt.twig
- Flutter (device_info_plus)
- Python (requests)
> flutter and python dependency upgrades

- templates/ruby/base/params.twig
- templates/ruby/base/requests/api.twig
- templates/ruby/base/requests/file.twig
- templates/ruby/lib/container/services/service.rb.twig
> feat: refactor ruby templates

- templates/go/base/params.twig
- templates/go/base/requests/api.twig
- templates/go/services/service.go.twig
> feat: refactor go templates

- templates/python/base/params.twig
- templates/python/base/requests/api.twig
- templates/python/base/requests/file.twig
- templates/python/package/services/service.py.twig
> feat: refactor python templates

- src/SDK/Language/Dart.php
- templates/flutter/base/requests/api.twig
- templates/flutter/base/requests/file.twig
- templates/flutter/base/utils.twig
- templates/flutter/lib/services/service.dart.twig
Fix alignment and spacing issues for Flutter SDK
Manual generate and compare
None
Yes
> Fix alignment and spacing issues for Flutter SDK

- templates/swift/Sources/Client.swift.twig
Fix for Swift chunked upload when using non-unique ID's
> Fix swift chunked upload when using non-unique ID

- templates/swift/Sources/OAuth/WebAuthComponent.swift.twig
- templates/swift/example-swiftui/Shared/ExampleViewModel.swift
- templates/swift/example-uikit/UIKitExample/ViewController.swift
Fix Swift OAuth cookie persistence
> Fix Swift OAuth cookie

- src/SDK/Language/Kotlin.php
Fix Kotlin array type parameter examples
Existing tests
Yes
> Manipulate array examples for Kotlin

- templates/android/LICENSE.md.twig
- templates/cli/LICENSE.md.twig
- templates/dart/LICENSE.twig
- templates/dart/lib/services/service.dart.twig
- templates/deno/LICENSE.twig
- templates/dotnet/LICENSE.twig
- templates/flutter/LICENSE.twig
- templates/go/LICENSE.twig
- templates/kotlin/LICENSE.md.twig
- templates/node/LICENSE.twig
- templates/php/LICENSE.twig
- templates/python/LICENSE.twig
- templates/ruby/LICENSE.twig
- templates/swift/LICENSE.twig
- templates/web/LICENSE.twig
Spacing fixes for Dart, license content rendered raw
https://github.com/appwrite/appwrite/pull/3726
YES
> Additional Fixes for Flutter & Dart release

- templates/dart/lib/src/models/model.dart.twig
> fix dart/glutter models spacing

- templates/kotlin/src/main/kotlin/io/appwrite/models/Model.kt.twig
- Fixes Kotlin SDK compilation error due to new models with no attributes, as data classes require at least one
Yes
> Fix Kotlin models with no properties

- templates/cli/.github/workflows/npm-publish.yml
- templates/node/.travis.yml.twig
- templates/web/.travis.yml.twig
- Allow NPM RC deployments based on tag name
Existing tests
Yes
> Allow NPM RC deployments

- templates/dart/lib/src/models/model.dart.twig
- templates/flutter/lib/src/realtime_message.dart.twig
- Fix realtime message timestamp data type
- Fix sub model arrays in dart (was iterator, convert to list)
YES
> fix realtime timestamp data type

- templates/android/library/src/main/java/io/appwrite/models/RealtimeModels.kt.twig
- templates/swift/Sources/Models/RealtimeModels.swift.twig
- templates/swift/Sources/Services/Realtime.swift.twig
- Fix timestamp type for realtime model
Existing tests
Yes
> Update swift client + android realtime timestamp type

- templates/kotlin/src/main/kotlin/io/appwrite/models/Model.kt.twig
Fix not accounting for additional properties when generating class vs data classes
Generated and built SDK via Appwrite
Yes
> Fix models with only additional properties

- templates/swift/Sources/Models/Model.swift.twig
Fix swift empty response models
Tested via playground with updated generated SDK
Yes
> Fix swift no param models

- templates/node/.travis.yml.twig
- templates/web/.travis.yml.twig
- Revert travis node versions to v14
Can't test
Yes
> Revert node version updates

- templates/ruby/base/params.twig
- templates/ruby/docs/example.md.twig
- templates/ruby/lib/container/services/service.rb.twig
- Fix Ruby template block ordering
Tested running locally built version with the playground
Yes
> Fix ruby services

- templates/android/library/src/main/java/io/appwrite/Role.kt.twig
- templates/dart/lib/role.dart.twig
- templates/deno/src/role.ts.twig
- templates/kotlin/src/main/kotlin/io/appwrite/Role.kt.twig
- templates/node/lib/role.js.twig
- templates/php/src/Role.php.twig
- templates/python/package/role.py.twig
- templates/ruby/lib/container/role.rb.twig
- templates/swift/Sources/Role.swift.twig
- templates/web/src/role.ts.twig
- tests/Base.php
- tests/FlutterBetaTest.php
- tests/FlutterStableTest.php
- tests/SwiftClient55Test.php
- tests/languages/android/Tests.kt
- tests/languages/dart/tests.dart
- tests/languages/deno/tests.ts
- tests/languages/flutter/tests.dart
- tests/languages/kotlin/Tests.kt
- tests/languages/node/test.js
- tests/languages/php/test.php
- tests/languages/python/tests.py
- tests/languages/ruby/tests.rb
- tests/languages/swift-client/Tests.swift
- tests/languages/swift-server/Tests.swift
- tests/languages/web/index.html
- tests/languages/web/node.js
- Add `member` function to all role helpers
- Add role helper tests
https://github.com/appwrite/appwrite/pull/3795
https://github.com/utopia-php/database/pull/183
Yes
> Add `member` function to all role helpers

- templates/php/src/Query.php.twig
- templates/python/package/query.py.twig
- tests/Base.php
- tests/languages/android/Tests.kt
- tests/languages/dart/tests.dart
- tests/languages/deno/tests.ts
- tests/languages/flutter/tests.dart
- tests/languages/kotlin/Tests.kt
- tests/languages/node/test.js
- tests/languages/php/test.php
- tests/languages/python/tests.py
- tests/languages/ruby/tests.rb
- tests/languages/swift-client/Tests.swift
- tests/languages/swift-server/Tests.swift
- tests/languages/web/index.html
- tests/languages/web/node.js
- Convert bool to lower case string for Python
- Convert bool to string equivalent for PHP
Added bool query tests
Fixes https://github.com/appwrite/sdk-for-python/issues/46
Yes
> Fix bool values in queries

- templates/android/library/src/main/java/io/appwrite/Role.kt.twig
- templates/dart/lib/role.dart.twig
- templates/deno/src/role.ts.twig
- templates/kotlin/src/main/kotlin/io/appwrite/Role.kt.twig
- templates/node/lib/role.js.twig
- templates/php/src/Role.php.twig
- templates/python/package/role.py.twig
- templates/ruby/lib/container/role.rb.twig
- templates/swift/Sources/Role.swift.twig
- templates/web/src/role.ts.twig
- tests/Base.php
- tests/languages/android/Tests.kt
- tests/languages/dart/tests.dart
- tests/languages/deno/tests.ts
- tests/languages/flutter/tests.dart
- tests/languages/kotlin/Tests.kt
- tests/languages/node/test.js
- tests/languages/php/test.php
- tests/languages/python/tests.py
- tests/languages/ruby/tests.rb
- tests/languages/swift-client/Tests.swift
- tests/languages/swift-server/Tests.swift
- tests/languages/web/index.html
- tests/languages/web/node.js
Add the `status` parameter to `users` and `user` roles  
> feat: add status helper

- templates/web/.travis.yml.twig
Adds the skip_cleanup flag to web sdk CI
NA 
> fix: web sdk CI issues

- templates/node/index.d.ts.twig
After introduction of Permission, Role and ID helper classes, Node type definition file was not updated. This PR adds these classes into Node typings.
- https://github.com/appwrite/sdk-for-node/issues/37
Yes 😇
> Fx: Node types

- templates/flutter/pubspec.yaml.twig
- templates/node/package.json.twig
Update SDK dependencies to latest
Existing tests
YES
> Feat dependency update

- templates/cli/Formula/formula.rb.twig
* https://github.com/appwrite/sdk-for-cli/issues/52
> Changes branch name from main to master

- src/SDK/Language/HTTP.php
- src/SDK/SDK.php
- src/Spec/Swagger2.php
- templates/android/docs/java/example.md.twig
- templates/android/docs/kotlin/example.md.twig
- templates/android/library/src/main/java/io/appwrite/services/ServiceTemplate.kt.twig
- templates/dart/base/requests/location.twig
- templates/dart/base/requests/oauth.twig
- templates/dart/docs/example.md.twig
- templates/deno/docs/example.md.twig
- templates/dotnet/docs/example.md.twig
- templates/dotnet/src/Appwrite/Services/ServiceTemplate.cs.twig
- templates/flutter/base/requests/location.twig
- templates/flutter/base/requests/oauth.twig
- templates/flutter/docs/example.md.twig
- templates/go/docs/example.md.twig
- templates/http/docs/example.md.twig
- templates/kotlin/base/utils.twig
- templates/kotlin/docs/java/example.md.twig
- templates/kotlin/docs/kotlin/example.md.twig
- templates/kotlin/src/main/kotlin/io/appwrite/services/ServiceTemplate.kt.twig
- templates/node/docs/example.md.twig
- templates/php/docs/example.md.twig
- templates/python/docs/example.md.twig
- templates/ruby/docs/example.md.twig
- templates/swift/base/params.twig
- templates/swift/docs/example.md.twig
- templates/web/docs/example.md.twig
- templates/web/src/services/template.ts.twig
Fix HTTP examples
- File uploads
- Differentiate method `security` and method `auth` to allow correct `set` methods in SDK examples and correct headers in HTTP examples. Rename existing usages to `auth` to align with what is represented by the spec.
Existing tests + manual docs checks
https://github.com/appwrite/sdk-generator/pull/577
Yes
> Fix http examples

- templates/dart/pubspec.yaml.twig
- templates/flutter/pubspec.yaml.twig
It updates a few dependencies.
Together with [these merged updates](https://github.com/appwrite/sdk-generator/pull/572) it will produce 10 more [pub.dev points](https://pub.dev/packages/appwrite/score) and fix following blocked dependencies:
FYI the [changelog](https://pub.dev/packages/flutter_web_auth_2/changelog) of the upgraded package.
Let the CI tests run.
Yes.
> Upgrade flutter_web_auth_2 and update dependencies

- templates/dart/lib/src/client_browser.dart.twig
- templates/flutter/lib/src/client_browser.dart.twig
- https://github.com/appwrite/appwrite/issues/4608
- https://github.com/appwrite/sdk-for-flutter/issues/81
> Fix Flutter Web Chunked upload

- templates/flutter/lib/package.dart.twig
- templates/flutter/lib/src/client_browser.dart.twig
- templates/flutter/lib/src/realtime_browser.dart.twig
- templates/flutter/pubspec.yaml.twig
- Removed Unused Import
- Change `dart:html/html.dart` to `package:universal_html/html.dart`
- Nothing major changed, no testing required
- Fixes https://github.com/appwrite/sdk-for-flutter/issues/88
Yes
> Feat: Improve Pub Points on `pub.dev`

- templates/swift/Sources/Client.swift.twig
- templates/swift/Sources/Services/Service.swift.twig
- Fix stack overflow recursion when storing a result without a type specified
- Fix parameter encoding
Existing + manual tests
N/A
Yes
> Feat swift generic updates

- templates/node/base/requests/file.twig
- templates/node/index.d.ts.twig
- templates/node/lib/inputFile.js.twig
* Fix InputFile helpers to avoid `toString()` because it can change the actual data and corrupt the upload
* Fix typing for InputFile to expose the constructor and use correct parameter types
* Fix chunk slicing because `slice()` takes a start and end rather than start and length
* Fix incorrect `Response` return type
Manually tested using playground-for-node and updated the `uploadFile()` function to:
```javascript
const { Readable } = require('stream');
const buffer = require('buffer');
const uploadFile = async () => {
console.log(chalk.greenBright('Running Upload File API'));
// const filepath = './resources/nature.jpg';
const filepath = './resources/big.png';
const filename = path.basename(filepath);
const fileBuffer = fs.readFileSync(filepath);
const fileBlob = new …
```
> Fix Node InputFile

- templates/flutter/lib/src/client_browser.dart.twig
Fix for
https://github.com/appwrite/sdk-for-flutter/issues/114
YES
> fix flutter web oauth issue

- templates/swift/Sources/Services/Service.swift.twig
- https://github.com/appwrite/sdk-for-apple/issues/26
> fix swift SDK when there was nested type

- src/SDK/Language/Swift.php
- templates/swift/Package.swift.twig
- templates/swift/Sources/JSONCodable/Codable+JSON.swift.twig
- templates/swift/Sources/Models/Model.swift.twig
- templates/swift/Sources/Services/Service.swift.twig
Fix swift builds by ensuring commas are correctly placed and there is no cyclic dependency on JSON+Codable
> Fix swift builds

- .travis.yml
- templates/flutter/lib/src/client_io.dart.twig
- templates/flutter/lib/src/cookie_manager.dart.twig
- templates/flutter/pubspec.yaml.twig
- tests/languages/flutter/tests.dart
- Fixes Flutter test for recent Flutter version. Issue arose from recent change to Flutter (https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests)
YES
> Flutter fix test for latest version

- CONTRIBUTING.md
- README.md
Reviews markdown files for grammar and readability. 
Manual review
> Grammar review by agency.

- templates/flutter/.travis.yml.twig
- With recent changes, packages depending in Flutter needs Flutter to deploy, deploy with dart only failed
YES
> Fix Flutter Deploy script

- composer.lock
- example.php
- package-lock.json
- templates/cli/index.js.twig
- templates/cli/lib/commands/command.js.twig
- templates/cli/lib/commands/deploy.js.twig
- templates/cli/lib/commands/generic.js.twig
- templates/cli/lib/commands/init.js.twig
- templates/cli/lib/parser.js.twig
1. Add the missing command description for the graphql command which was causing the CLI to fail
2. Set max width for the command help descriptions 
> fix: cli errors

- templates/dart/lib/src/input_file.dart.twig
- templates/flutter/example/pubspec.yaml.twig
- tests/languages/dart/tests.dart
- tests/languages/flutter/tests.dart
- Update InputFile interface
YES
> update inputfile for dart and flutter

- templates/dart/lib/src/client_io.dart.twig
- templates/flutter/.travis.yml.twig
- templates/flutter/lib/src/client_io.dart.twig
> fix flutter travis script - cd to build dir

- src/SDK/Language/Flutter.php
- templates/flutter/lib/src/client_offline_mixin.dart.twig
- templates/flutter/lib/src/offline_db_io.dart.twig
- templates/flutter/lib/src/offline_db_stub.dart.twig
- templates/flutter/lib/src/offline_db_web.dart.twig
- templates/flutter/pubspec.yaml.twig
To ensure sqflite works on Windows and Linux, sqflite_common_ffi is required.
Manual
Previous PRs:
* https://github.com/appwrite/sdk-generator/pull/627
* https://github.com/appwrite/sdk-generator/pull/618
Yes
> Ensure offline support works in linux

- templates/dart/README.md.twig
- templates/flutter/README.md.twig
Fix flutter installation command - pub get to pub add
* https://github.com/appwrite/appwrite/issues/5277
Yes
> fix flutter install command : pub get -> pub add

- templates/cli/lib/commands/deploy.js.twig
Fixing variable deployment when creating functions
[x] Manual testing
Closes https://github.com/appwrite/sdk-for-cli/issues/59
Yes
> Fix CLI function variables deploying

- composer.lock
- example.php
- templates/cli/lib/parser.js.twig
Add missing command description to the CLI
> fix: add missing command description to the CLI

- templates/deno/src/client.ts.twig
Hi!
I think it could allow a slight optimization and I think that with the following article: https://www.builder.io/blog/double-equal-vs-triple-equal
Yeah
> refactor: slight optimization

- templates/flutter/pubspec.yaml.twig
- templates/node/package.json.twig
- Upgrade SDK dependencies
YES
> upgrade dependencies

- templates/android/docs/java/example.md.twig
- templates/android/docs/kotlin/example.md.twig
- templates/dart/docs/example.md.twig
- templates/deno/docs/example.md.twig
- templates/dotnet/docs/example.md.twig
- templates/flutter/docs/example.md.twig
- templates/go/docs/example.md.twig
- templates/kotlin/docs/java/example.md.twig
- templates/kotlin/docs/kotlin/example.md.twig
- templates/node/docs/example.md.twig
- templates/php/docs/example.md.twig
- templates/python/docs/example.md.twig
- templates/ruby/docs/example.md.twig
- templates/swift/docs/example.md.twig
- templates/web/docs/example.md.twig
Update code examples to go to cloud.appwrite.io
> Update code examples to go to cloud

- templates/dotnet/docs/example.md.twig
Fix documentation for delete methods 
> Fix dotnet delete method docs

- templates/flutter/pubspec.yaml.twig
- fix failing test due to dependency conflict from last update, missed that test was failing, due to other unrelated failing test
> fix for failing flutter test

- templates/dart/lib/src/client_io.dart.twig
> fix user agent

- templates/dotnet/docs/example.md.twig
Add missing `using` directive to the `/docs/examples` template for the .NET SDK
No
Yes
> doc: Update .NET SDK docs examples template

- templates/swift/base/requests/OAuth.twig
A [previous PR](https://github.com/appwrite/sdk-generator/pull/703) fixed the params and path for the rest of the SDK, but this was missed.
Manually generated SDK:
* https://github.com/appwrite/sdk-generator/pull/703
Yes
> Fix swift params and path

- templates/cli/lib/commands/init.js.twig
Add V3 Tag to functions pull in CLI
Yes
> Add V3 Tag to functions pull in CLI

- templates/swift/Sources/Client.swift.twig
Fixes https://github.com/appwrite/sdk-generator/pull/716
* https://github.com/appwrite/sdk-generator/pull/716
> add missing error type while throwing error

- templates/node/index.d.ts.twig
Fixes https://github.com/appwrite/sdk-generator/issues/726
Generated type file:
* https://github.com/appwrite/sdk-generator/issues/726
Yes
> Fix node sdk typing for Role.label()

- src/SDK/Language/CLI.php
- templates/cli/lib/commands/deploy.js.twig
- templates/cli/lib/commands/init.js.twig
- templates/cli/lib/paginate.js.twig
- templates/cli/lib/questions.js.twig
- Add scaling timeout for attribute/index create/delete
- Add pagination
Manual test + existing tests
https://github.com/appwrite/appwrite/issues/6915
Yes
> Feat CLI pagination

- src/SDK/Language/Deno.php
- src/SDK/Language/JS.php
- src/SDK/Language/Node.php
- templates/node/lib/enums/enum.js.twig
- templates/web/src/enums/enum.ts.twig
- tests/languages/node/test.js
Fix node enum casing
Updated existing tests
> Ensure pascal case used for node enums

- templates/ruby/docs/example.md.twig
Update example.md.twig
Should be `require 'appwrite`
> Fixes require for generated reference examples.

- templates/ruby/lib/container/client.rb.twig
> Remove nil values from params

- templates/ruby/lib/container/models/model.rb.twig
> Fix Ruby accessor

- templates/dart/lib/services/service.dart.twig
- templates/flutter/lib/services/service.dart.twig
Fixes type errors that fails to compile the app
n/a
yes
> Fix: Enum Type errors in Flutter and Dart

- templates/cli/lib/commands/deploy.js.twig
- templates/cli/lib/paginate.js.twig
Update old function query format to new JSON format.
Manually deployed to 1.5:
None
Yes
> Update CLI to use new query format

- templates/cli/README.md.twig
> Update brew install command

- src/SDK/Language.php
- src/SDK/Language/Kotlin.php
- src/SDK/Language/Swift.php
- templates/deno/src/enums/enum.ts.twig
- templates/node/lib/enums/enum.js.twig
- templates/python/package/enums/enum.py.twig
- templates/ruby/lib/container/enums/enum.rb.twig
Fix enum keys with non-ascii characters
Existing tests
> Properly handle non-ascii characters for all languages enum keys

- src/SDK/Language/Kotlin.php
> Force enum package name

- src/SDK/Language/DotNet.php
> Fix dotnet enum collisions

- templates/python/setup.py.twig
> Fix setup packages

- templates/android/scripts/publish-module.gradle
> Fix javadoc task

- templates/cli/lib/commands/generic.js.twig
Fixes https://github.com/appwrite/sdk-for-cli/issues/116
Manual:
- https://github.com/appwrite/sdk-for-cli/issues/116 
Yes
> Update login to use new auth method

- templates/node/.travis.yml.twig
- templates/web/.travis.yml.twig
Make sure if we create a tag with lowercase -rc, it's still published as a pre-release
None
Yes
> Update node and web checks to be case insensitive

- templates/php/src/Query.php.twig
- tests/languages/php/test.php
Fix PHP contains parameter types
Fixed tests
https://github.com/appwrite/sdk-for-php/issues/29
> Fix PHP contains

- templates/web/src/client.ts.twig
- Fix realtime unsubscribe, closes socket connection
YES
> close realtime socket properly on unsubscribe

- templates/android/library/build.gradle.twig
Fix Android SDK compile issues with Android Gradle Plugin version greater than 8.2
> Test removing okhttp BOM

- templates/dart/lib/src/client_browser.dart.twig
- templates/flutter/lib/src/client_browser.dart.twig
- Fix type definition linter issue
> Fix type definition linter issue in flutter and Dart

- templates/cli/lib/client.js.twig
This change enables appwrite-cli to capture all cookies in 'set-cookie' response headers.
Fixes https://github.com/appwrite/sdk-for-cli/issues/110
> appwrite cli login issue - Update client.js.twig

- templates/react-native/.github/workflows/publish.yml.twig
> React Native - handle both -rc and -RC releases

- src/SDK/Language/ReactNative.php
Fix file type for react native SDK
YES
> Fix react native File type

- templates/cli/index.js.twig
- templates/cli/lib/commands/generic.js.twig
- templates/cli/lib/parser.js.twig
Adding the `appwrite whoami` command for getting basic account information and verifying user login status.
> feat(cli): Adding console whoami command

- example.php
Upgrade CLI response to latest
> refactor(cli): Review fixing

- templates/cli/lib/commands/pull.js.twig
- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/questions.js.twig
Adds the ability to pull resources at once 
https://github.com/appwrite/sdk-generator/assets/316103/8718ff60-548a-464b-8156-2f360491f2da
> Feat push pull all

- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/spinner.js.twig
> feat(cli): Showing deployed function URL

- templates/dart/.github/workflows/publish.yml.twig
- templates/flutter/.github/workflows/publish.yml.twig
- Fix flutter and dart publish workflow
YES
> Fix Flutter and Dart Publish workflow

- templates/dotnet/.github/workflows/publish.yml.twig
Fix broken nuget push line continuation
> Single line command

- templates/cli/index.js.twig
- templates/cli/lib/questions.js.twig
- templates/cli/package.json.twig
Added searchable list to all paginate data
> feat: Added list search

- templates/cli/lib/commands/init.js.twig
- Fetching function templates using API.
- When the user reached API `rate-limit` then failing back to current folder-based fetching
> Feat function init improvments

- src/SDK/Language/PHP.php
> Fix PHP numbers typed as int

- .github/ISSUE_TEMPLATE/bug.yaml
The template uses very old versions of Appwrite, this updates them. Although a better idea would be to fallback to [template at the organization level](https://github.com/appwrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug.yaml).
N/A.
N/A.
Yes.
> Update Appwrite Versions

- templates/cli/lib/commands/push.js.twig
> fix(cli): Apply non destructive changes

- templates/android/library/src/main/java/io/package/Client.kt.twig
- templates/android/library/src/main/java/io/package/ID.kt.twig
- templates/android/library/src/main/java/io/package/Permission.kt.twig
- templates/android/library/src/main/java/io/package/Query.kt.twig
- templates/android/library/src/main/java/io/package/Service.kt.twig
Added inline docs comments for the Android SDK templates.
https://github.com/appwrite/sdk-generator/issues/679
https://github.com/appwrite/sdk-generator/pull/671
> Inline docs for android SDK templates

- templates/flutter/lib/src/client.dart.twig
- templates/flutter/lib/src/client_browser.dart.twig
- templates/flutter/lib/src/realtime.dart.twig
- templates/flutter/lib/src/realtime_browser.dart.twig
- templates/flutter/pubspec.yaml.twig
I update the flutter code to use the new js_interop (https://dart.dev/interop/js-interop). I did replace universal_http with package web and dart.library.html with dart.library.js_interop
> Update flutter code to use js_interop

- templates/php/src/Query.php.twig
\-
https://github.com/appwrite/sdk-for-php/issues/31
yes
> Fixed jsonSerialize returntype in php query template 

- composer.lock
- templates/cli/index.js.twig
- templates/cli/lib/commands/generic.js.twig
- templates/cli/lib/commands/init.js.twig
- templates/cli/lib/commands/pull.js.twig
- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/commands/run.js.twig
- templates/cli/lib/config.js.twig
- templates/cli/lib/emulation/docker.js.twig
- templates/cli/lib/emulation/utils.js.twig
- templates/cli/lib/parser.js.twig
- templates/cli/lib/questions.js.twig
- templates/cli/lib/sdks.js.twig
Improves quality of CLI 2.0 changes
x
Yes
> Feat: CLI QA improvements

- templates/cli/lib/commands/run.js.twig
- templates/cli/lib/emulation/docker.js.twig
- templates/cli/lib/emulation/utils.js.twig
- Mark Docker logs gray, and user's logs white
- Fix missing imports (warning after 1 hour, user impersonation)
x
Yes
> Fix: CLI Developmetn QA

- templates/cli/lib/commands/run.js.twig
- templates/cli/lib/emulation/docker.js.twig
Allows multiple function to run at the same time, by cleaning up only function-specific containers.
x
Yes
> Fix: Dev function cleanup experience

- templates/cli/lib/commands/push.js.twig
Increases timeout to properly visualise when pushing many functions
x
Yes
> Fix: CLI Push timeout

- templates/cli/lib/commands/pull.js.twig
- templates/cli/lib/questions.js.twig
Improves flow to prevent unwanted code pulling. Includes ability to automate for CI/CD
x
Yes
> Fix: Pull function's code flow

- templates/cli/lib/commands/run.js.twig
- templates/cli/lib/emulation/utils.js.twig
Ensures `run function` respects scopes in appwrite.json, to more precisely replicate production post-push.
x
Yes
> Fix: CLI run scopes

- templates/cli/lib/commands/generic.js.twig
- templates/cli/lib/commands/pull.js.twig
- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/spinner.js.twig
> Fix cli qa

- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/config.js.twig
Applying push logic for indexes, recreating, deleting and adding.
> feat(cli): Pushing logic for indexes

- templates/cli/lib/commands/generic.js.twig
- templates/cli/lib/commands/pull.js.twig
- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/config.js.twig
- templates/cli/lib/spinner.js.twig
* https://github.com/appwrite/sdk-for-cli/issues/135
> feat(cli): Custom debounce limit

- templates/cli/lib/emulation/docker.js.twig
Ensures port is open before printing success message
x
Yes
> Feat: CLI local development port checker

- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/questions.js.twig
- tests/Base.php
Applies changes to make push confirmation experience better.
x
Yes
> Fix: push confirmation

- templates/apple/Package.swift.twig
- templates/swift/Package.swift.twig
Fix issue where previously cached version of dependency satisfied constraint so was not updated to new required minimum
Existing tests
> Update swift minimum deps versions

- templates/cli/lib/commands/pull.js.twig
Try to fetch the last function deployment for local code pulling.
On any error, we will resort to the local value
Locally
> feat(cli): Pull last deployment instead of local when available

- templates/cli/lib/commands/init.js.twig
- templates/cli/lib/commands/pull.js.twig
- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/config.js.twig
Config will read the `appwrite.json` file from the current folder or any of the parent directories
> Feat run from sub folders

- templates/cli/lib/commands/pull.js.twig
- templates/cli/lib/commands/push.js.twig
- consistent `pull` commands
- wording for `deploy` command
> fix(cli): consistent command description

- src/Spec/Swagger2.php
> chore: fix sdk generator

- src/SDK/Language/Go.php
> fix(go): bug fix

- templates/android/docs/java/example.md.twig
- templates/android/docs/kotlin/example.md.twig
- templates/dart/docs/example.md.twig
- templates/deno/docs/example.md.twig
- templates/dotnet/docs/example.md.twig
- templates/flutter/docs/example.md.twig
- templates/go/docs/example.md.twig
- templates/graphql/docs/example.md.twig
- templates/kotlin/docs/java/example.md.twig
- templates/kotlin/docs/kotlin/example.md.twig
- templates/node/docs/example.md.twig
- templates/php/docs/example.md.twig
- templates/python/docs/example.md.twig
- templates/react-native/docs/example.md.twig
- templates/rest/docs/example.md.twig
- templates/ruby/docs/example.md.twig
- templates/swift/docs/example.md.twig
- templates/web/docs/example.md.twig
- tests/resources/spec.json
Fixes : 
```js
.setProject('&lt;YOUR_PROJECT_ID&gt;');
```
to 
```js
.setProject('<YOUR_PROJECT_ID>');
```
Manual.
N/A.
Yes.
> Fix: incorrect encoding.

- templates/dart/pubspec.yaml.twig
- templates/flutter/pubspec.yaml.twig
- Upgrade dependencies
- no functionality change
YES
> Upgrade flutter and dart dependencies

- templates/web/src/client.ts.twig
- templates/web/src/services/template.ts.twig
> fix(web): reverting to previous webauth redirect logic

- templates/cli/lib/commands/pull.js.twig
> feat(cli): pulling variable to .env only

- templates/php/src/Services/Service.php.twig
> fix(php): wrong condition

- src/SDK/Language/Go.php
- templates/go/payload.go.twig
- templates/php/src/Payload.php.twig
- tests/languages/go/tests.go
Refactoring of the Go & PHP payload methods
> Refactor php and go multipart

- templates/cli/lib/commands/run.js.twig
- templates/cli/lib/config.js.twig
- templates/cli/lib/emulation/docker.js.twig
We couldn't run the function within nested folders using CLI. 
> Fix path for directory

- composer.json
- composer.lock
> Update deps for twig advisory

- mock-server/app/http.php
- tests/languages/go/tests.go
- tests/resources/spec.json
> feat: adding tests for compiled languages

- composer.lock
- templates/python/package/multipart.py.twig
- templates/python/package/payload.py.twig
> Fixed to_string and to_binary for python

- templates/android/.github/workflows/autoclose.yml
- templates/apple/.github/workflows/autoclose.yml
- templates/cli/.github/workflows/autoclose.yml
- templates/dart/.github/workflows/autoclose.yml
- templates/deno/.github/workflows/autoclose.yml
- templates/dotnet/.github/workflows/autoclose.yml
- templates/flutter/.github/workflows/autoclose.yml
- templates/go/.github/workflows/autoclose.yml
- templates/graphql/.github/workflows/autoclose.yml
- templates/kotlin/.github/workflows/autoclose.yml
- templates/node/.github/workflows/autoclose.yml
- templates/php/.github/workflows/autoclose.yml
- templates/python/.github/workflows/autoclose.yml
- templates/react-native/.github/workflows/autoclose.yml
- templates/rest/.github/workflows/autoclose.yml
- templates/ruby/.github/workflows/autoclose.yml
- templates/swift/.github/workflows/autoclose.yml
- templates/web/.github/workflows/autoclose.yml
> Adding autoclose workflow

- templates/dotnet/Package/Client.cs.twig
closes #963 
Manually on several files in all sizes
> fix: dotnet uploads

- templates/ruby/.github/workflows/publish.yml.twig
> Fix Ruby publish

- mock-server/app/http.php
- templates/node/src/client.ts.twig
- templates/web/src/client.ts.twig
- tests/Base.php
- tests/Node16Test.php
- tests/Node18Test.php
- tests/Node20Test.php
- tests/WebChromiumTest.php
- tests/WebNodeTest.php
- tests/languages/node/test.js
- tests/languages/web/index.html
- tests/languages/web/node.js
Adds hardcoded `ping()` method to client, for Node and Web
Related PR: https://github.com/appwrite/appwrite/pull/8761
> feat: ping endpoint

- templates/ruby/.github/workflows/publish.yml.twig
> Fix secrets templating

- templates/android/example/src/main/java/io/package/android/ui/accounts/AccountsViewModel.kt.twig
- templates/swift/example-uikit/UIKitExample/ViewController.swift
- tests/languages/android/Tests.kt
- tests/languages/apple/Tests.swift
- tests/languages/flutter/tests.dart
- tests/languages/web/index.html
> Fix: Test endpoints

- templates/react-native/src/services/template.ts.twig
- templates/web/src/services/template.ts.twig
This PR removed adding of params from uri as they are already added before using `Service.flatten`, which leads to duplicate addtion.
https://github.com/appwrite/sdk-for-web/issues/114
Yes.
> fix: remove duplicate param

- src/SDK/Language/CLI.php
- templates/cli/lib/commands/organizations.js.twig
- templates/cli/lib/questions.js.twig
- templates/cli/lib/utils.js.twig
replaces teamsList with organizationsList in sdk-for-cli due to recent billing changes.
Yes.
> chore: add listOrganizations to sdk-for-cli

- templates/dart/lib/src/client_mixin.dart.twig
- templates/flutter/lib/src/client_mixin.dart.twig
For consistency.
Manual.
N/A.
Yes.
> Use `Mixin` for Flutter/Dart

- templates/cli/.github/workflows/npm-publish.yml
Add the fix that was not added to generator before: 
- https://github.com/appwrite/sdk-for-cli/pull/145/files
> fix: qemu-system package

- templates/react-native/package.json.twig
Updates dependencies in react-native sdk to fix expo doctor errors.
Before:
Now:
- https://github.com/appwrite/sdk-for-react-native/issues/43
Yes.
> chore: update dependencies in react-native

- templates/react-native/src/client.ts.twig
Fix build error in react-native
before:
after:
Yes.
> fix: build error in react-native

- templates/node/src/client.ts.twig
- templates/web/src/client.ts.twig
chuckedUpload method leads to this error in generated SDK:
No more warning/error.
Yes.
> fix: file can be undefined warning

- templates/dotnet/Package/Models/Model.cs.twig
fix build error for dotnet.
before:
after:
yes.
> fix: dotnet build error

- mock-server/src/Utopia/Exception.php
> chore: improve route not found error message

- src/Spec/Swagger2.php
> Read multi-method auth

- templates/react-native/src/client.ts.twig
- templates/web/src/client.ts.twig
> fix: remove credentials include when devKeys are present

- templates/swift/README.md.twig
Fix sdk name in swift readme.
- https://github.com/appwrite/sdk-for-swift/issues/34
yes.
> docs: update README to correct package name for Swift SDK

- templates/go/docs/example.md.twig
Fixes client and service initialization syntax in Go SDK docs examples
Generate Go examples and visit `docs/`
- Before
- After
(this change is reflected across every single SDK example)
No
Yes
> Fix Go SDK docs examples

- templates/cli/.github/workflows/npm-publish.yml
- templates/node/.github/workflows/publish.yml.twig
- templates/react-native/.github/workflows/publish.yml.twig
- templates/web/.github/workflows/publish.yml.twig
update the env in publish workflows
yes.
> chore: update npm publish workflows to use NPM_TOKEN_NO_ORG

- templates/react-native/src/models.ts.twig
- templates/swift/README.md.twig
fix models not having defaultdocument, defaultpreferences etc.
yes.
> fix: use correct sdk name + fix models in react native

- src/Spec/Spec.php
- src/Spec/Swagger2.php
> Feat: Multiple namespaces

- templates/go/README.md.twig
> fix and improve readme for go sdk

- src/Spec/Swagger2.php
Before -
After -
1. Databases -
2. Some other service -
Manual
N/A.
Yes.
> Fix: methods being duplicated across services

- src/SDK/Language/ReactNative.php
- src/SDK/Language/Web.php
- templates/node/src/services/template.ts.twig
- templates/react-native/src/services/template.ts.twig
- templates/web/src/services/template.ts.twig
removes readonly attributes from payload
yes.
> feat: filter readonly attributes

- src/SDK/Language/Dart.php
- templates/dart/.github/workflows/test.yml
Add a GH workflow to make sure the SDK builds and tests pass.
Tested and confirmed the workflow was created successfully:
* https://github.com/appwrite/sdk-generator/pull/1151
Yes
> chore(dart): add GitHub workflow to analyze and test

- templates/deno/docs/example.md.twig
- templates/node/docs/example.md.twig
- templates/react-native/docs/example.md.twig
- templates/web/docs/example.md.twig
```js
import { Client, Account } from "packageName";
const client = new Client()
.setEndpoint('https://<REGION>.cloud.appwrite.io/v1') // Your API Endpoint
.setProject('<YOUR_PROJECT_ID>'); // Your project ID
const account = new Account(client);
const result = await account.create({
userId: '<USER_ID>',
email: 'email@example.com',
password: '',
name: '<NAME>'
});
console.log(result);
```
> Use object style params for examples

- src/SDK/Language/Flutter.php
- templates/dart/lib/package.dart.twig
- templates/flutter/lib/package.dart.twig
> Fix dash instead of snake

- src/SDK/Language/Go.php
- templates/go/docs/example.md.twig
- templates/go/models/model.go.twig
> Fix go file paths + docs

- templates/android/library/src/main/java/io/package/services/Service.kt.twig
- templates/kotlin/src/main/kotlin/io/appwrite/services/ServiceTemplate.kt.twig
> Fix deprecated android + kotlin

- templates/cli/index.js.twig
- templates/cli/lib/commands/pull.js.twig
- templates/cli/lib/commands/push.js.twig
- templates/cli/lib/questions.js.twig
Fix new terminology to prevent CLI issues
Community QA
x
Yes
> Fix: grid DB CLI
